[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ufsm"
version = "0.1.0"
authors = [
  { name="Jonas Blixt", email="jonpe960@gmail.com" },
]
description = "uFSM statechart tool"
readme = "README.rst"
requires-python = ">=3.9"
dependencies = [
    "typing-extensions",
    "pyside6>=6.7",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD3 License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jonasblixt/ufsm"
"Bug Tracker" = "https://github.com/jonasblixt/ufsm/issues"

[project.scripts]
ufsm = "ufsm.__main__:main"

[tool.setuptools]
packages = ["ufsm"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
# See: https://docs.astral.sh/ruff/rules/ for details
select = ["ALL"]
ignore = [
    "COM812",   # Conflicts with the formatter
    "ISC001",   # Conflicts with the formatter
    "ANN101",   # "missing-type-self"
    "PLE0605",  # ruff does not handle += in __all__
    "FBT",      # don't care for these at the moment
    "PT001",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "PT004",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "PT005",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "PT023",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "N802",     # For pyside6 compability
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = [
    "^build.*",
]
