#ifndef COMMON_H
#define COMMON_H

enum ufsmm_selection {
    UFSMM_SELECTION_NONE,
    UFSMM_SELECTION_STATE,
    UFSMM_SELECTION_REGION,
    UFSMM_SELECTION_TRANSITION,
    UFSMM_SELECTION_ENTRY,
    UFSMM_SELECTION_EXIT,
    UFSMM_SELECTION_ACTION,
    UFSMM_SELECTION_GUARD,
    UFSMM_SELECTION_MULTI,
};

enum ufsmm_resize_selector {
    UFSMM_NO_SELECTION,
    UFSMM_TOP_LEFT,
    UFSMM_TOP_MIDDLE,
    UFSMM_TOP_RIGHT,
    UFSMM_RIGHT_MIDDLE,
    UFSMM_BOT_RIGHT,
    UFSMM_BOT_MIDDLE,
    UFSMM_BOT_LEFT,
    UFSMM_LEFT_MIDDLE
};

#endif
