/* Autogenerated with uFSM */

#include "test_init_to_nested.h"


int test_init_to_nested_init(struct test_init_to_nested_machine *m, void *user)
{
    for (unsigned int i = 0; i < 3; i++) {
        m->wsv[i] = 0;
        m->csv[i] = 0;
    }
    m->head = 0;
    m->tail = 0;
    m->user = user;
    return 0;
}

int test_init_to_nested_process(struct test_init_to_nested_machine *m, unsigned int event)
{
    for (unsigned int i = 0; i < 3; i++)
        m->wsv[i] = 0;

    switch(event) {
        case UFSM_RESET:
            m->wsv[1] = 2; // Ar2 = B2
            m->wsv[0] = 1; // Root = A
            m->wsv[2] = 3; // Ar1 = B1
            B1Init(m->user);
            eA(m->user);
            eB1(m->user);
            B2Init(m->user);
            eB2(m->user);
        break;
        default:
            return -UFSM_BAD_ARGUMENT;
    }
    for (unsigned int i = 0; i < 3; i++)
        if(m->wsv[i] != 0)
            m->csv[i] = m->wsv[i];

    return 0;
}
