/* Autogenerated with uFSM */

#include "test_nested_composits.h"


int test_nested_composits_init(struct test_nested_composits_machine *m, void *user)
{
    for (unsigned int i = 0; i < 6; i++) {
        m->wsv[i] = 0;
        m->csv[i] = 0;
    }
    m->head = 0;
    m->tail = 0;
    m->user = user;
    return 0;
}

int test_nested_composits_process(struct test_nested_composits_machine *m, unsigned int event)
{
    unsigned int process_auto_transition = 0;
process_more:

    for (unsigned int i = 0; i < 6; i++)
        m->wsv[i] = 0;

    switch(event) {
        case UFSM_RESET:
            m->wsv[1] = 2; // Ar2 = A21
            m->wsv[3] = 6; // A1r3 = A13
            m->wsv[4] = 7; // A1r2 = A12
            m->wsv[5] = 9; // A1r1 = A11
            m->wsv[2] = 10; // Ar1 = InitA
            m->wsv[0] = 1; // Root = A
            eInitA(m->user);
            eA21(m->user);
        break;
        case EV3:
            /* A21 -> A22 */
            if ((m->csv[1] == 2) && (m->csv[0] == 1)) {
                /* Exit actions */
                if ((m->csv[1] == 2) && (m->csv[0] == 1)) {
                    xA21(m->user);
                }
                /* Actions */
                /* Entry actions */
                m->wsv[1] = 3; // Ar2 = A22
                eA22(m->user);
            }
            /* A22 -> A21 */
            if ((m->csv[1] == 3) && (m->csv[0] == 1)) {
                /* Exit actions */
                if ((m->csv[1] == 3) && (m->csv[0] == 1)) {
                    xA22(m->user);
                }
                /* Actions */
                /* Entry actions */
                m->wsv[1] = 2; // Ar2 = A21
                eA21(m->user);
            }
        break;
        case EV:
            /* InitA -> A1 */
            if ((m->csv[2] == 10) && (m->csv[0] == 1)) {
                /* Exit actions */
                if ((m->csv[2] == 10) && (m->csv[0] == 1)) {
                    xInitA(m->user);
                }
                /* Actions */
                /* Entry actions */
                m->wsv[2] = 5; // Ar1 = A1
                if ((m->wsv[2] == 5)) {
                    m->wsv[5] = 9; // A1r1 = A11
                    eA11(m->user);
                }
                if ((m->wsv[2] == 5)) {
                    m->wsv[4] = 7; // A1r2 = A12
                    eA12(m->user);
                }
                if ((m->wsv[2] == 5)) {
                    m->wsv[3] = 6; // A1r3 = A13
                    eA13(m->user);
                }
                process_auto_transition = 1;
            }
        break;
        case EV2:
            /* A12 -> A12dummy */
            if ((m->csv[4] == 7) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                /* Exit actions */
                if ((m->csv[4] == 7) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    xA12(m->user);
                }
                /* Actions */
                /* Entry actions */
                m->wsv[4] = 8; // A1r2 = A12dummy
                eA12dummy(m->user);
                process_auto_transition = 1;
            }
        break;
        case EV_B:
            /* A -> B */
            if ((m->csv[0] == 1)) {
                /* Exit actions */
                if ((m->csv[3] == 6) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    xA13(m->user);
                }
                if ((m->csv[4] == 8) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    xA12dummy(m->user);
                }
                if ((m->csv[4] == 7) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    xA12(m->user);
                }
                if ((m->csv[5] == 9) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    xA11(m->user);
                }
                if ((m->csv[1] == 3) && (m->csv[0] == 1)) {
                    xA22(m->user);
                }
                if ((m->csv[1] == 2) && (m->csv[0] == 1)) {
                    xA21(m->user);
                }
                if ((m->csv[2] == 10) && (m->csv[0] == 1)) {
                    xInitA(m->user);
                }
                /* Actions */
                /* Entry actions */
                m->wsv[0] = 11; // Root = B
                eB(m->user);
            }
        break;
        case UFSM_AUTO_TRANSITION:
            process_auto_transition = 0;
            /* Join -> AEnd */
            if ((m->csv[3] == 6) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                if ((m->csv[4] == 8) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                    if ((m->csv[5] == 9) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                        /* Exit actions */
                        if ((m->csv[3] == 6) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                            xA13(m->user);
                        }
                        if ((m->csv[4] == 8) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                            xA12dummy(m->user);
                        }
                        if ((m->csv[4] == 7) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                            xA12(m->user);
                        }
                        if ((m->csv[5] == 9) && (m->csv[2] == 5) && (m->csv[0] == 1)) {
                            xA11(m->user);
                        }
                        /* Actions */
                        /* Entry actions */
                        m->wsv[2] = 4; // Ar1 = AEnd
                        eAEnd(m->user);
                    }
                }
            }
        break;
        default:
            return -UFSM_BAD_ARGUMENT;
    }
    for (unsigned int i = 0; i < 6; i++)
        if(m->wsv[i] != 0)
            m->csv[i] = m->wsv[i];

    if (process_auto_transition == 1) {
        event = UFSM_AUTO_TRANSITION;
        goto process_more;
    }
    return 0;
}
