/* Autogenerated with uFSM */
#ifndef UFSM_TEST_NESTED_COMPOSITS
#define UFSM_TEST_NESTED_COMPOSITS

#define UFSM_OK 0
#define UFSM_BAD_ARGUMENT 1
#define UFSM_SIGNAL_QUEUE_FULL 2

/* Events */
#define UFSM_RESET 0
#define UFSM_AUTO_TRANSITION 1
#define EV3 10
#define EV 11
#define EV2 12
#define EV_B 13

/* Signals */

/* Guard prototypes */

/* Action prototypes */
void eInitA(void *user);
void xInitA(void *user);
void eAEnd(void *user);
void eA11(void *user);
void xA11(void *user);
void eA21(void *user);
void xA21(void *user);
void eA22(void *user);
void xA22(void *user);
void eA12dummy(void *user);
void xA12dummy(void *user);
void eA13(void *user);
void xA13(void *user);
void eA12(void *user);
void xA12(void *user);
void eB(void *user);

struct test_nested_composits_machine {
    unsigned int csv[6];
    unsigned int wsv[6];
    unsigned int signal[8];
    unsigned int head;
    unsigned int tail;
    void *user;
};

int test_nested_composits_init(struct test_nested_composits_machine *m, void *user);
int test_nested_composits_process(struct test_nested_composits_machine *m, unsigned int event);

#endif  // UFSM_TEST_NESTED_COMPOSITS
