#ifndef UFSM_COLORS_H
#define UFSM_COLORS_H

enum ufsmm_color_theme {
    UFSMM_COLOR_THEME_DARK,
    UFSMM_COLOR_THEME_LIGHT,
};

enum ufsmm_color {
    UFSMM_COLOR_BG,
    UFSMM_COLOR_RED1,
    UFSMM_COLOR_GREEN1,
    UFSMM_COLOR_YELLOW1,
    UFSMM_COLOR_BLUE1,
    UFSMM_COLOR_PURPLE1,
    UFSMM_COLOR_AQUA1,
    UFSMM_COLOR_GRAY1,
    UFSMM_COLOR_GRAY2,
    UFSMM_COLOR_RED2,
    UFSMM_COLOR_GREEN2,
    UFSMM_COLOR_YELLOW2,
    UFSMM_COLOR_BLUE2,
    UFSMM_COLOR_PURPLE2,
    UFSMM_COLOR_AQUA2,
    UFSMM_COLOR_FG,
    UFSMM_COLOR_BG0_H,
    UFSMM_COLOR_BG0,
    UFSMM_COLOR_BG1,
    UFSMM_COLOR_BG2,
    UFSMM_COLOR_BG3,
    UFSMM_COLOR_BG4,
    UFSMM_COLOR_GRAY3,
    UFSMM_COLOR_ORANGE1,
    UFSMM_COLOR_BG0_S,
    UFSMM_COLOR_FG4,
    UFSMM_COLOR_FG3,
    UFSMM_COLOR_FG2,
    UFSMM_COLOR_FG1,
    UFSMM_COLOR_FG0,
    UFSMM_COLOR_ORANGE2,
};

#endif
