/* Automatically generated by uFSM version 1.0.0 */

#include "canvas.h"

/* Forward declaration of states and regions */
const struct ufsm_region r_00000000_0000_0000_0000_000000000000; /* Region: Root */
const struct ufsm_state s_9bc407ce_cf13_4456_b060_9742ec032659; /* State: Main */
const struct ufsm_state s_8f355b8a_b35b_413e_aa59_6975b26c60f6; /* State: Init */
const struct ufsm_state s_96f83830_76b5_43b5_97f6_eeb7f5b74510; /* State: Selection */
const struct ufsm_state s_3f3cbe39_6420_4c24_b653_9da89a7a08e2; /* State: Pan */
const struct ufsm_state s_d192cdf5_2e61_4224_a429_b90403b1ec0e; /* State: Scale */
const struct ufsm_region r_7dc97c5b_572b_44ac_ae00_ab897e427d21; /* Region: Object Selection */
const struct ufsm_state s_c01acffd_075f_4cb7_a3e4_ddba8d0cab7f; /* State: Init */
const struct ufsm_state s_9fa03fc8_a545_4536_9ab4_6bf405dd9780; /* State: Select */
const struct ufsm_state s_353c633d_e736_4464_81a1_90466dade15d; /* State: Region */
const struct ufsm_state s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10; /* State: Multi select */
const struct ufsm_state s_306e164b_3b1b_4fa4_93e3_1628a8fb054c; /* State: Entry selected */
const struct ufsm_state s_566c339a_2e94_4e8e_847e_507d1a039d8f; /* State: Resize state */
const struct ufsm_state s_0ca836f8_de8d_42bf_99ed_16a0d40e3541; /* State: State */
const struct ufsm_state s_71b9383e_a54c_4c13_94a9_75f5674af90f; /* State: Transition */
const struct ufsm_state s_6fe1a397_5832_4d54_b332_afe219b0657b; /* State: Move vertice */
const struct ufsm_state s_4b1878b4_404c_407e_8a33_4e2ef72cdae6; /* State: Text block */
const struct ufsm_state s_6af64093_51b3_4564_be9a_fcb682134262; /* State: Guard */
const struct ufsm_state s_7921f170_0693_4d0b_bc73_b4567901a39b; /* State: Action */
const struct ufsm_state s_c955e985_b169_4bce_b36a_70d31da164c5; /* State: Exit selected */
const struct ufsm_state s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb; /* State: Resize text block */
const struct ufsm_state s_5bb316a6_0cd5_4fdc_99d1_f19d74c17ffd; /* State: Move State */
const struct ufsm_state s_1e103c0b_8094_4d00_831d_0e2bdc7ecf14; /* State: Resize state */
const struct ufsm_region r_c9493679_2229_4958_91a6_03288aa25eab; /* Region: New region */
const struct ufsm_region r_c089e9d0_46e3_4f36_92cc_5fc7c8cf7ab0; /* Region: New region */
const struct ufsm_state s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1; /* State: Resize region */
const struct ufsm_region r_7cd89eb7_af2b_4a61_86ca_40bcd3a7d520; /* Region: New region */
const struct ufsm_state s_50565759_c7e0_426f_948e_1cbc276a1204; /* State: Move State */
const struct ufsm_region r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2; /* Region: Tool controller */
const struct ufsm_state s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c; /* State: Tool */
const struct ufsm_state s_ab4fecb3_a182_4199_b3c9_32a4d900ee28; /* State: Init */
const struct ufsm_state s_411c1230_4754_443b_90d6_f2c471efe170; /* State: State */
const struct ufsm_state s_ad9bbeee_0628_402e_92dd_684a4a35de9b; /* State: Region */
const struct ufsm_state s_20cef1d5_aa6d_4418_a109_833bad1003d2; /* State: Transition */
const struct ufsm_state s_9b32f09f_6ffc_4587_ba5e_82f3ea05b4f3; /* State: Final */
const struct ufsm_state s_80904f43_c8d8_42fd_b771_3b62987f92d3; /* State: Final */
const struct ufsm_state s_0a4d49d9_c0ce_45ff_aa6a_81f95e9e98fc; /* State: Final */
const struct ufsm_region r_b31f9254_ea60_4f9d_bfd5_3780fab7dde3; /* Region: Transition tools */
const struct ufsm_region r_1875929f_f938_4a5b_a695_e6a578848da0; /* Region: Region tools */
const struct ufsm_state s_afb7a57a_f268_49d7_8834_3955d80f534c; /* State: Init */
const struct ufsm_state s_51ff5faa_b548_4b41_b3eb_1576932e9fe7; /* State: Region tools */
const struct ufsm_state s_09ed5b3c_d326_46bc_8ae1_f1377e942207; /* State: Add */
const struct ufsm_state s_981f9378_69f5_43fe_b5dc_9d20146f8512; /* State: New state */
const struct ufsm_state s_de4a6839_98a3_4ad2_b3e8_afd201ff2526; /* State: Final */
const struct ufsm_state s_5577a77a_a350_4e46_b546_d8e30a5a4218; /* State: New transition */
const struct ufsm_state s_61e6d20a_06ae_484d_b503_b553a57076fb; /* State: Final */
const struct ufsm_state s_9e7cfc8f_eaad_49e7_af0c_62ef54a95902; /* State: Final */
const struct ufsm_state s_251f5542_7682_4cbb_bcdf_658d352b4ac7; /* State: Final */
const struct ufsm_state s_a3597828_1b7e_4269_ba3a_1c77e960c864; /* State: Final */
const struct ufsm_region r_399603a6_1dcf_4977_9a02_948ace6516e8; /* Region: New region */
const struct ufsm_state s_0aba8ad4_38a9_4738_9804_0ea11c158a5b; /* State: Start */
const struct ufsm_state s_fc6399d1_c9b5_4a38_88d7_755d83db66e7; /* State: End */
const struct ufsm_state s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41; /* State: Vertice */
const struct ufsm_state s_4bc349e7_ed14_49e2_a5c6_5e279183799f; /* State: Final */
const struct ufsm_region r_a50feb78_b194_4729_bfcf_65232ca6637f; /* Region: New region */
const struct ufsm_state s_579a57b9_4811_47b4_bcb3_e29e3d5bfbd0; /* State: Start */
const struct ufsm_state s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc; /* State: End */
const struct ufsm_region r_f38bf7dc_626b_47b8_bafa_50a13beea4e2; /* Region: State tools */
const struct ufsm_state s_ee8b0968_9dd9_4249_bdc8_cfb8795dc5d8; /* State: Init */
const struct ufsm_state s_960d3c90_38ca_4b40_ba58_3fa52185d2c2; /* State: State tools */
const struct ufsm_state s_d5563896_3314_42c4_af48_de144f157b2e; /* State: Final */
const struct ufsm_state s_ed5c60cd_007c_45e9_bbf2_b28b9bee2f65; /* State: Final */
const struct ufsm_state s_79b42026_e0d8_4aea_bf1b_b131d28f76c2; /* State: Final */
const struct ufsm_state s_4f8688ed_1d77_4105_a8c3_32d2a01b4323; /* State: Final */
const struct ufsm_state s_d00443ac_2597_4673_82b0_e9b6349e5700; /* State: Add */
const struct ufsm_state s_9dcc0d0a_9027_433a_98a9_6484ee801210; /* State: Edit */
const struct ufsm_state s_57bf38bf_9f31_452c_ae58_04890f81958a; /* State: Final */
const struct ufsm_state s_8962e8ae_4db8_4d87_b944_36c1e883fc43; /* State: Final */
const struct ufsm_state s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2; /* State: Delete */
const struct ufsm_state s_4fa41c00_4c8a_427b_aab9_084185816cf2; /* State: Final */
const struct ufsm_state s_a4974753_4d25_4df5_b50d_c2c54682884a; /* State: Final */
const struct ufsm_state s_5eb13eb8_b839_4876_9195_15171db9d107; /* State: Final */

/* Triggers */
const struct ufsm_trigger trigger_147c056e_9041_4a99_bad7_c5c25b13104a = {
    .name = "eLMBDown",
    .trigger = eLMBDown,
};

const struct ufsm_trigger trigger_ea5929ab_c6d9_4cee_90eb_9544709d6034 = {
    .name = "eLMBUp",
    .trigger = eLMBUp,
};

const struct ufsm_trigger trigger_b3971a16_8744_4c8c_a7a0_676033b2e187 = {
    .name = "eRMBDown",
    .trigger = eRMBDown,
};

const struct ufsm_trigger trigger_ae622a23_f651_4fab_bad2_ecfbd96d2883 = {
    .name = "eRMBUp",
    .trigger = eRMBUp,
};

const struct ufsm_trigger trigger_060051ac_b9c7_4b85_b478_dcdf54362f21 = {
    .name = "eMotion",
    .trigger = eMotion,
};

const struct ufsm_trigger trigger_46272102_bbf8_4c57_9178_d4feb1d5ea5a = {
    .name = "eEnablePan",
    .trigger = eEnablePan,
};

const struct ufsm_trigger trigger_946bce31_1110_4b1d_ab94_d1c439c41b62 = {
    .name = "eDisablePan",
    .trigger = eDisablePan,
};

const struct ufsm_trigger trigger_9e6d72de_0fec_4145_a66c_797f21520f1a = {
    .name = "eKeyDown",
    .trigger = eKeyDown,
};

const struct ufsm_trigger trigger_038dda91_a2e0_45c9_8ed5_c264dc60e5d9 = {
    .name = "eUserAbort",
    .trigger = eUserAbort,
};

const struct ufsm_trigger trigger_69fa9c3b_1c87_4766_8dee_abf2742d5023 = {
    .name = "eToolError",
    .trigger = eToolError,
};

const struct ufsm_trigger trigger_59f70ac3_315a_41c6_97db_06fbafd06f02 = {
    .name = "eZoomIn",
    .trigger = eZoomIn,
};

const struct ufsm_trigger trigger_4768a897_3963_4965_94d4_d2975eaffe26 = {
    .name = "eZoomOut",
    .trigger = eZoomOut,
};

const struct ufsm_trigger trigger_faf24206_d5cc_4593_8f94_2951717e6154 = {
    .name = "eKey_r_down",
    .trigger = eKey_r_down,
};

const struct ufsm_trigger trigger_14ee1854_d31e_4144_bd11_005095ca8d93 = {
    .name = "eKey_esc_down",
    .trigger = eKey_esc_down,
};

const struct ufsm_trigger trigger_93f84b98_6e9e_4acb_8011_6c758d37ba1b = {
    .name = "eKey_e_down",
    .trigger = eKey_e_down,
};

const struct ufsm_trigger trigger_6153e3ce_a758_469e_b559_b8f06b691d7a = {
    .name = "eKey_x_down",
    .trigger = eKey_x_down,
};

const struct ufsm_trigger trigger_a5bd1392_5461_489e_ad96_12bec38ed212 = {
    .name = "eKey_a_down",
    .trigger = eKey_a_down,
};

const struct ufsm_trigger trigger_abdf4bb1_e569_4bc1_b984_8b08b5366cf4 = {
    .name = "eMove",
    .trigger = eMove,
};

const struct ufsm_trigger trigger_94c4dde3_d5b5_44ea_82ec_9e8b55e37892 = {
    .name = "eDelete",
    .trigger = eDelete,
};

const struct ufsm_trigger trigger_8026ece2_dd00_44e8_8613_a68197aaec7c = {
    .name = "eKey_s_down",
    .trigger = eKey_s_down,
};

const struct ufsm_trigger trigger_2dcc8a3e_f0b8_4e8a_96a0_a339f4dc3bfb = {
    .name = "eKey_t_down",
    .trigger = eKey_t_down,
};

const struct ufsm_trigger trigger_ff3ba5c8_93e8_430e_b37a_8196a4be36fa = {
    .name = "eKey_delete_down",
    .trigger = eKey_delete_down,
};

const struct ufsm_trigger trigger_aa3e0691_1994_453b_b506_d9e2400ca6d9 = {
    .name = "eKey_shift_down",
    .trigger = eKey_shift_down,
};

const struct ufsm_trigger trigger_477900d8_124e_45b9_99d9_4e2aca45fe1d = {
    .name = "eKey_shift_up",
    .trigger = eKey_shift_up,
};

const struct ufsm_trigger trigger_312affef_dc71_4190_93b8_b8b3f2623d71 = {
    .name = "eKey_i_down",
    .trigger = eKey_i_down,
};

const struct ufsm_trigger trigger_5436ff7d_0fcb_4cfb_bd94_e82f14913849 = {
    .name = "eKey_f_down",
    .trigger = eKey_f_down,
};

const struct ufsm_trigger trigger_6ef41bf3_e96c_467e_8d44_ca20342a8c3f = {
    .name = "eSaveModel",
    .trigger = eSaveModel,
};

const struct ufsm_trigger trigger_e229b0c4_18ec_4b88_82ab_d4b8bea28c37 = {
    .name = "eEnableScale",
    .trigger = eEnableScale,
};

const struct ufsm_trigger trigger_94c820d7_bb72_43f0_be6a_09ccf6ad8134 = {
    .name = "eDisableScale",
    .trigger = eDisableScale,
};

const struct ufsm_trigger trigger_c3bf0ec6_1fa5_480b_a7ca_71c9b0a124de = {
    .name = "eScrollUp",
    .trigger = eScrollUp,
};

const struct ufsm_trigger trigger_bbc53dc1_e6ff_4a0f_85eb_b3d9d82ade5c = {
    .name = "eScrollDown",
    .trigger = eScrollDown,
};

const struct ufsm_region r_00000000_0000_0000_0000_000000000000 = {
    .index = 0,
    .name = "Root",
    .has_history = false,
    .state = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .parent_state = NULL,
    .next = NULL,
};

/* Transitions originating from 'Main' */
const struct ufsm_transition t_2d426111_3a43_4b1a_806c_429a58933591;
const struct ufsm_transition t_a6c9ad6d_0290_4175_a002_2a36de53e02d;
const struct ufsm_action a_75d67fbb_4c7b_49d3_8dca_37738d7ea3b9;
const struct ufsm_transition t_dc093791_23cf_44ee_9a7f_be11c3af735e;
const struct ufsm_action a_0d8610a3_0667_4da7_967c_b6aaa115bb00;
const struct ufsm_transition t_09dd9b8a_6758_4c30_ab8a_2301cecb65c0;

const struct ufsm_transition t_2d426111_3a43_4b1a_806c_429a58933591 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = NULL,
    .guard = NULL,
    .source = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .dest = &s_96f83830_76b5_43b5_97f6_eeb7f5b74510,
    .next = &t_a6c9ad6d_0290_4175_a002_2a36de53e02d,
};

const struct ufsm_action a_75d67fbb_4c7b_49d3_8dca_37738d7ea3b9 = {
    .name = "canvas_store_offset",
    .f = &canvas_store_offset,
    .next = NULL,
};

const struct ufsm_transition t_a6c9ad6d_0290_4175_a002_2a36de53e02d = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_46272102_bbf8_4c57_9178_d4feb1d5ea5a,
    .action = &a_75d67fbb_4c7b_49d3_8dca_37738d7ea3b9,
    .guard = NULL,
    .source = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .dest = &s_3f3cbe39_6420_4c24_b653_9da89a7a08e2,
    .next = &t_dc093791_23cf_44ee_9a7f_be11c3af735e,
};

const struct ufsm_action a_0d8610a3_0667_4da7_967c_b6aaa115bb00 = {
    .name = "canvas_save_model",
    .f = &canvas_save_model,
    .next = NULL,
};

const struct ufsm_transition t_dc093791_23cf_44ee_9a7f_be11c3af735e = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_6ef41bf3_e96c_467e_8d44_ca20342a8c3f,
    .action = &a_0d8610a3_0667_4da7_967c_b6aaa115bb00,
    .guard = NULL,
    .source = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .dest = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = &t_09dd9b8a_6758_4c30_ab8a_2301cecb65c0,
};

const struct ufsm_transition t_09dd9b8a_6758_4c30_ab8a_2301cecb65c0 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_e229b0c4_18ec_4b88_82ab_d4b8bea28c37,
    .action = NULL,
    .guard = NULL,
    .source = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .dest = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .next = NULL,
};

const struct ufsm_state s_9bc407ce_cf13_4456_b060_9742ec032659 = {
    .index = 0,
    .name = "Main",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_2d426111_3a43_4b1a_806c_429a58933591,
    .entry = NULL,
    .exit = NULL,
    .region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .parent_region = &r_00000000_0000_0000_0000_000000000000,
    .next = &s_8f355b8a_b35b_413e_aa59_6975b26c60f6,
};

/* Transitions originating from 'Init' */
const struct ufsm_transition t_d2aaf618_7ded_41d5_93cf_e6717b8de7b5;
const struct ufsm_action a_17420595_e8e5_48a1_8ebc_c9c022f13feb;

const struct ufsm_action a_17420595_e8e5_48a1_8ebc_c9c022f13feb = {
    .name = "canvas_select_root_region",
    .f = &canvas_select_root_region,
    .next = NULL,
};

const struct ufsm_transition t_d2aaf618_7ded_41d5_93cf_e6717b8de7b5 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_17420595_e8e5_48a1_8ebc_c9c022f13feb,
    .guard = NULL,
    .source = &s_8f355b8a_b35b_413e_aa59_6975b26c60f6,
    .dest = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = NULL,
};

const struct ufsm_state s_8f355b8a_b35b_413e_aa59_6975b26c60f6 = {
    .index = 1,
    .name = "Init",
    .kind = UFSM_STATE_INIT,
    .transition = &t_d2aaf618_7ded_41d5_93cf_e6717b8de7b5,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_00000000_0000_0000_0000_000000000000,
    .next = &s_96f83830_76b5_43b5_97f6_eeb7f5b74510,
};

/* Entry functions for state 'Selection' */
const struct ufsm_entry_exit entry_9bbe200f_f1f8_459f_b964_9bc89915ef0c;
const struct ufsm_entry_exit entry_9bbe200f_f1f8_459f_b964_9bc89915ef0c = {
    .name = "canvas_process_selection",
    .f = &canvas_process_selection,
    .next = NULL,
};

/* Transitions originating from 'Selection' */
const struct ufsm_transition t_65a23640_7596_4ba0_9448_9f20c000de48;

const struct ufsm_transition t_65a23640_7596_4ba0_9448_9f20c000de48 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_ea5929ab_c6d9_4cee_90eb_9544709d6034,
    .action = NULL,
    .guard = NULL,
    .source = &s_96f83830_76b5_43b5_97f6_eeb7f5b74510,
    .dest = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = NULL,
};

const struct ufsm_state s_96f83830_76b5_43b5_97f6_eeb7f5b74510 = {
    .index = 2,
    .name = "Selection",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_65a23640_7596_4ba0_9448_9f20c000de48,
    .entry = &entry_9bbe200f_f1f8_459f_b964_9bc89915ef0c,
    .exit = NULL,
    .region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .parent_region = &r_00000000_0000_0000_0000_000000000000,
    .next = &s_3f3cbe39_6420_4c24_b653_9da89a7a08e2,
};

/* Transitions originating from 'Pan' */
const struct ufsm_transition t_04ece7bb_e03b_453c_86cd_eddd3573b248;
const struct ufsm_transition t_ffa1104c_81c0_4abc_8285_5e4119ca657b;
const struct ufsm_action a_c87a0df9_6b2e_4590_98e3_f575ecd05cca;

const struct ufsm_transition t_04ece7bb_e03b_453c_86cd_eddd3573b248 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_946bce31_1110_4b1d_ab94_d1c439c41b62,
    .action = NULL,
    .guard = NULL,
    .source = &s_3f3cbe39_6420_4c24_b653_9da89a7a08e2,
    .dest = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = &t_ffa1104c_81c0_4abc_8285_5e4119ca657b,
};

const struct ufsm_action a_c87a0df9_6b2e_4590_98e3_f575ecd05cca = {
    .name = "canvas_update_offset",
    .f = &canvas_update_offset,
    .next = NULL,
};

const struct ufsm_transition t_ffa1104c_81c0_4abc_8285_5e4119ca657b = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_c87a0df9_6b2e_4590_98e3_f575ecd05cca,
    .guard = NULL,
    .source = &s_3f3cbe39_6420_4c24_b653_9da89a7a08e2,
    .dest = &s_3f3cbe39_6420_4c24_b653_9da89a7a08e2,
    .next = NULL,
};

const struct ufsm_state s_3f3cbe39_6420_4c24_b653_9da89a7a08e2 = {
    .index = 3,
    .name = "Pan",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_04ece7bb_e03b_453c_86cd_eddd3573b248,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_00000000_0000_0000_0000_000000000000,
    .next = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
};

/* Transitions originating from 'Scale' */
const struct ufsm_transition t_2414b1c9_ade6_4cca_8af7_08c564240324;
const struct ufsm_action a_a252ea9f_f2ba_413c_b730_01c00fa84297;
const struct ufsm_transition t_763b0c37_a490_406d_99f0_dcfc5890f740;
const struct ufsm_transition t_2c1bc37e_b4a7_44a9_9fb3_15de5f3fc9ac;
const struct ufsm_action a_1b1dc80d_75ad_43c3_8f1c_2c43750bdc18;

const struct ufsm_action a_a252ea9f_f2ba_413c_b730_01c00fa84297 = {
    .name = "canvas_inc_scale",
    .f = &canvas_inc_scale,
    .next = NULL,
};

const struct ufsm_transition t_2414b1c9_ade6_4cca_8af7_08c564240324 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_c3bf0ec6_1fa5_480b_a7ca_71c9b0a124de,
    .action = &a_a252ea9f_f2ba_413c_b730_01c00fa84297,
    .guard = NULL,
    .source = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .dest = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .next = &t_763b0c37_a490_406d_99f0_dcfc5890f740,
};

const struct ufsm_transition t_763b0c37_a490_406d_99f0_dcfc5890f740 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_94c820d7_bb72_43f0_be6a_09ccf6ad8134,
    .action = NULL,
    .guard = NULL,
    .source = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .dest = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = &t_2c1bc37e_b4a7_44a9_9fb3_15de5f3fc9ac,
};

const struct ufsm_action a_1b1dc80d_75ad_43c3_8f1c_2c43750bdc18 = {
    .name = "canvas_dec_scale",
    .f = &canvas_dec_scale,
    .next = NULL,
};

const struct ufsm_transition t_2c1bc37e_b4a7_44a9_9fb3_15de5f3fc9ac = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_bbc53dc1_e6ff_4a0f_85eb_b3d9d82ade5c,
    .action = &a_1b1dc80d_75ad_43c3_8f1c_2c43750bdc18,
    .guard = NULL,
    .source = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .dest = &s_d192cdf5_2e61_4224_a429_b90403b1ec0e,
    .next = NULL,
};

const struct ufsm_state s_d192cdf5_2e61_4224_a429_b90403b1ec0e = {
    .index = 4,
    .name = "Scale",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_2414b1c9_ade6_4cca_8af7_08c564240324,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_00000000_0000_0000_0000_000000000000,
    .next = NULL,
};

const struct ufsm_region r_7dc97c5b_572b_44ac_ae00_ab897e427d21 = {
    .index = 1,
    .name = "Object Selection",
    .has_history = false,
    .state = &s_c01acffd_075f_4cb7_a3e4_ddba8d0cab7f,
    .parent_state = &s_96f83830_76b5_43b5_97f6_eeb7f5b74510,
    .next = NULL,
};

/* Transitions originating from 'Init' */
const struct ufsm_transition t_d4648cf6_67f7_4118_b3eb_ce9382b5748e;

const struct ufsm_transition t_d4648cf6_67f7_4118_b3eb_ce9382b5748e = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_c01acffd_075f_4cb7_a3e4_ddba8d0cab7f,
    .dest = &s_9fa03fc8_a545_4536_9ab4_6bf405dd9780,
    .next = NULL,
};

const struct ufsm_state s_c01acffd_075f_4cb7_a3e4_ddba8d0cab7f = {
    .index = 5,
    .name = "Init",
    .kind = UFSM_STATE_INIT,
    .transition = &t_d4648cf6_67f7_4118_b3eb_ce9382b5748e,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_9fa03fc8_a545_4536_9ab4_6bf405dd9780,
};

/* Transitions originating from 'Select' */
const struct ufsm_transition t_05be9ba2_6bde_499b_9db1_f1c7c6a867f7;
const struct ufsm_guard g_b4ee4f42_946d_4e5d_b2bc_ed44fdd10df5;
const struct ufsm_transition t_c6261e9a_00b0_4c9c_8e39_77482611a303;
const struct ufsm_guard g_070dc5b4_104f_4b61_b2e3_c7a25a93693d;
const struct ufsm_transition t_dbd92d5c_3903_4b27_b659_af475bd9dbbf;
const struct ufsm_guard g_82cd571f_3318_4549_bbcf_a16918c493db;

const struct ufsm_guard g_b4ee4f42_946d_4e5d_b2bc_ed44fdd10df5 = {
    .name = "canvas_state_selected",
    .f = &canvas_state_selected,
    .next = NULL,
};

const struct ufsm_transition t_05be9ba2_6bde_499b_9db1_f1c7c6a867f7 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_b4ee4f42_946d_4e5d_b2bc_ed44fdd10df5,
    .source = &s_9fa03fc8_a545_4536_9ab4_6bf405dd9780,
    .dest = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
    .next = &t_c6261e9a_00b0_4c9c_8e39_77482611a303,
};

const struct ufsm_guard g_070dc5b4_104f_4b61_b2e3_c7a25a93693d = {
    .name = "canvas_region_selected",
    .f = &canvas_region_selected,
    .next = NULL,
};

const struct ufsm_transition t_c6261e9a_00b0_4c9c_8e39_77482611a303 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_070dc5b4_104f_4b61_b2e3_c7a25a93693d,
    .source = &s_9fa03fc8_a545_4536_9ab4_6bf405dd9780,
    .dest = &s_353c633d_e736_4464_81a1_90466dade15d,
    .next = &t_dbd92d5c_3903_4b27_b659_af475bd9dbbf,
};

const struct ufsm_guard g_82cd571f_3318_4549_bbcf_a16918c493db = {
    .name = "canvas_transition_selected",
    .f = &canvas_transition_selected,
    .next = NULL,
};

const struct ufsm_transition t_dbd92d5c_3903_4b27_b659_af475bd9dbbf = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_82cd571f_3318_4549_bbcf_a16918c493db,
    .source = &s_9fa03fc8_a545_4536_9ab4_6bf405dd9780,
    .dest = &s_71b9383e_a54c_4c13_94a9_75f5674af90f,
    .next = NULL,
};

const struct ufsm_state s_9fa03fc8_a545_4536_9ab4_6bf405dd9780 = {
    .index = 6,
    .name = "Select",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_05be9ba2_6bde_499b_9db1_f1c7c6a867f7,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_353c633d_e736_4464_81a1_90466dade15d,
};

/* Entry functions for state 'Region' */
const struct ufsm_entry_exit entry_e149cd17_441b_4525_a60a_2b836f0b4f17;
const struct ufsm_entry_exit entry_e149cd17_441b_4525_a60a_2b836f0b4f17 = {
    .name = "canvas_check_rresize_boxes",
    .f = &canvas_check_rresize_boxes,
    .next = NULL,
};

/* Transitions originating from 'Region' */
const struct ufsm_transition t_35b67067_970f_4a34_9bb4_2af935ffaa03;
const struct ufsm_guard g_b2b3dfa5_c27c_4fbc_98a9_8058345cf84e;
const struct ufsm_transition t_668319e0_a3c4_41a1_b01a_f416d0111a43;

const struct ufsm_guard g_b2b3dfa5_c27c_4fbc_98a9_8058345cf84e = {
    .name = "canvas_region_resize_selected",
    .f = &canvas_region_resize_selected,
    .next = NULL,
};

const struct ufsm_transition t_35b67067_970f_4a34_9bb4_2af935ffaa03 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_b2b3dfa5_c27c_4fbc_98a9_8058345cf84e,
    .source = &s_353c633d_e736_4464_81a1_90466dade15d,
    .dest = &s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1,
    .next = &t_668319e0_a3c4_41a1_b01a_f416d0111a43,
};

const struct ufsm_transition t_668319e0_a3c4_41a1_b01a_f416d0111a43 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = NULL,
    .guard = NULL,
    .source = &s_353c633d_e736_4464_81a1_90466dade15d,
    .dest = &s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10,
    .next = NULL,
};

const struct ufsm_state s_353c633d_e736_4464_81a1_90466dade15d = {
    .index = 7,
    .name = "Region",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_35b67067_970f_4a34_9bb4_2af935ffaa03,
    .entry = &entry_e149cd17_441b_4525_a60a_2b836f0b4f17,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10,
};

/* Entry functions for state 'Multi select' */
const struct ufsm_entry_exit entry_80d892d7_8f52_4436_9bb1_b47d81a0b675;
const struct ufsm_entry_exit entry_80d892d7_8f52_4436_9bb1_b47d81a0b675 = {
    .name = "canvas_begin_mselect",
    .f = &canvas_begin_mselect,
    .next = NULL,
};

/* Exit functions for state 'Multi select' */
const struct ufsm_entry_exit exit_ac79b491_2580_4287_8556_ef15584067a1;
const struct ufsm_entry_exit exit_ac79b491_2580_4287_8556_ef15584067a1 = {
    .name = "canvas_end_mselect",
    .f = &canvas_end_mselect,
    .next = NULL,
};

/* Transitions originating from 'Multi select' */
const struct ufsm_transition t_da088bd7_62af_4c59_8b0c_fee2bff0d575;
const struct ufsm_action a_6323cb5d_6eb8_4807_96e8_5859ab24f563;

const struct ufsm_action a_6323cb5d_6eb8_4807_96e8_5859ab24f563 = {
    .name = "canvas_update_mselect",
    .f = &canvas_update_mselect,
    .next = NULL,
};

const struct ufsm_transition t_da088bd7_62af_4c59_8b0c_fee2bff0d575 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_6323cb5d_6eb8_4807_96e8_5859ab24f563,
    .guard = NULL,
    .source = &s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10,
    .dest = &s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10,
    .next = NULL,
};

const struct ufsm_state s_c5650f0f_0bdd_4ab5_8b90_d37ba79c7a10 = {
    .index = 8,
    .name = "Multi select",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_da088bd7_62af_4c59_8b0c_fee2bff0d575,
    .entry = &entry_80d892d7_8f52_4436_9bb1_b47d81a0b675,
    .exit = &exit_ac79b491_2580_4287_8556_ef15584067a1,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_306e164b_3b1b_4fa4_93e3_1628a8fb054c,
};

/* Entry functions for state 'Entry selected' */
const struct ufsm_entry_exit entry_e2efd678_f38f_4508_a7e5_bc6c0b02df09;
const struct ufsm_entry_exit entry_e2efd678_f38f_4508_a7e5_bc6c0b02df09 = {
    .name = "canvas_focus_entry",
    .f = &canvas_focus_entry,
    .next = NULL,
};

/* Transitions originating from 'Entry selected' */
const struct ufsm_transition t_e2642724_a630_4c0c_9901_2cc25ce0e8dc;
const struct ufsm_action a_717852d1_9b12_4e3a_a5c2_23afb76ae947;

const struct ufsm_action a_717852d1_9b12_4e3a_a5c2_23afb76ae947 = {
    .name = "canvas_reorder_entry_func",
    .f = &canvas_reorder_entry_func,
    .next = NULL,
};

const struct ufsm_transition t_e2642724_a630_4c0c_9901_2cc25ce0e8dc = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_717852d1_9b12_4e3a_a5c2_23afb76ae947,
    .guard = NULL,
    .source = &s_306e164b_3b1b_4fa4_93e3_1628a8fb054c,
    .dest = &s_306e164b_3b1b_4fa4_93e3_1628a8fb054c,
    .next = NULL,
};

const struct ufsm_state s_306e164b_3b1b_4fa4_93e3_1628a8fb054c = {
    .index = 9,
    .name = "Entry selected",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_e2642724_a630_4c0c_9901_2cc25ce0e8dc,
    .entry = &entry_e2efd678_f38f_4508_a7e5_bc6c0b02df09,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_566c339a_2e94_4e8e_847e_507d1a039d8f,
};

/* Transitions originating from 'Resize state' */
const struct ufsm_transition t_6e597e40_5261_41bb_8f1b_1301e7665bfb;
const struct ufsm_action a_239df017_ddd2_4b00_9f1a_dc4a628a642d;

const struct ufsm_action a_239df017_ddd2_4b00_9f1a_dc4a628a642d = {
    .name = "canvas_resize_state",
    .f = &canvas_resize_state,
    .next = NULL,
};

const struct ufsm_transition t_6e597e40_5261_41bb_8f1b_1301e7665bfb = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_239df017_ddd2_4b00_9f1a_dc4a628a642d,
    .guard = NULL,
    .source = &s_566c339a_2e94_4e8e_847e_507d1a039d8f,
    .dest = &s_566c339a_2e94_4e8e_847e_507d1a039d8f,
    .next = NULL,
};

const struct ufsm_state s_566c339a_2e94_4e8e_847e_507d1a039d8f = {
    .index = 10,
    .name = "Resize state",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_6e597e40_5261_41bb_8f1b_1301e7665bfb,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
};

/* Entry functions for state 'State' */
const struct ufsm_entry_exit entry_acc71ec2_ac0b_4d98_8097_b18871163fcc;
const struct ufsm_entry_exit entry_7977a736_1b6d_4516_8f5b_3268f5b58097;
const struct ufsm_entry_exit entry_acc71ec2_ac0b_4d98_8097_b18871163fcc = {
    .name = "canvas_check_sresize_boxes",
    .f = &canvas_check_sresize_boxes,
    .next = &entry_7977a736_1b6d_4516_8f5b_3268f5b58097,
};

const struct ufsm_entry_exit entry_7977a736_1b6d_4516_8f5b_3268f5b58097 = {
    .name = "canvas_check_action_func",
    .f = &canvas_check_action_func,
    .next = NULL,
};

/* Transitions originating from 'State' */
const struct ufsm_transition t_a393faff_3d7b_4919_8ec5_06cf0e54ca7c;
const struct ufsm_action a_7395f054_fc48_4353_be0b_614eb7499478;
const struct ufsm_guard g_f9d5b4d4_5ffe_4e1e_add4_11cb3e0782a9;
const struct ufsm_transition t_c33d6574_3641_428f_862c_25c85ff0ccbf;
const struct ufsm_guard g_3878b253_54a4_4eee_9185_d88f3f2126d1;
const struct ufsm_transition t_a832561d_14c4_4157_9142_673305be9a55;
const struct ufsm_guard g_7d572f7b_a690_4072_b499_5bb256f9feb4;
const struct ufsm_transition t_d6576de2_6011_4513_a900_e25a293dc40d;

const struct ufsm_action a_7395f054_fc48_4353_be0b_614eb7499478 = {
    .name = "canvas_resize_state_begin",
    .f = &canvas_resize_state_begin,
    .next = NULL,
};

const struct ufsm_guard g_f9d5b4d4_5ffe_4e1e_add4_11cb3e0782a9 = {
    .name = "canvas_state_resize_selected",
    .f = &canvas_state_resize_selected,
    .next = NULL,
};

const struct ufsm_transition t_a393faff_3d7b_4919_8ec5_06cf0e54ca7c = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_7395f054_fc48_4353_be0b_614eb7499478,
    .guard = &g_f9d5b4d4_5ffe_4e1e_add4_11cb3e0782a9,
    .source = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
    .dest = &s_566c339a_2e94_4e8e_847e_507d1a039d8f,
    .next = &t_c33d6574_3641_428f_862c_25c85ff0ccbf,
};

const struct ufsm_guard g_3878b253_54a4_4eee_9185_d88f3f2126d1 = {
    .name = "canvas_state_entry_selected",
    .f = &canvas_state_entry_selected,
    .next = NULL,
};

const struct ufsm_transition t_c33d6574_3641_428f_862c_25c85ff0ccbf = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_3878b253_54a4_4eee_9185_d88f3f2126d1,
    .source = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
    .dest = &s_306e164b_3b1b_4fa4_93e3_1628a8fb054c,
    .next = &t_a832561d_14c4_4157_9142_673305be9a55,
};

const struct ufsm_guard g_7d572f7b_a690_4072_b499_5bb256f9feb4 = {
    .name = "canvas_state_exit_selected",
    .f = &canvas_state_exit_selected,
    .next = NULL,
};

const struct ufsm_transition t_a832561d_14c4_4157_9142_673305be9a55 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_7d572f7b_a690_4072_b499_5bb256f9feb4,
    .source = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
    .dest = &s_c955e985_b169_4bce_b36a_70d31da164c5,
    .next = &t_d6576de2_6011_4513_a900_e25a293dc40d,
};

const struct ufsm_transition t_d6576de2_6011_4513_a900_e25a293dc40d = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = NULL,
    .guard = NULL,
    .source = &s_0ca836f8_de8d_42bf_99ed_16a0d40e3541,
    .dest = &s_50565759_c7e0_426f_948e_1cbc276a1204,
    .next = NULL,
};

const struct ufsm_state s_0ca836f8_de8d_42bf_99ed_16a0d40e3541 = {
    .index = 11,
    .name = "State",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_a393faff_3d7b_4919_8ec5_06cf0e54ca7c,
    .entry = &entry_acc71ec2_ac0b_4d98_8097_b18871163fcc,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_71b9383e_a54c_4c13_94a9_75f5674af90f,
};

/* Entry functions for state 'Transition' */
const struct ufsm_entry_exit entry_830247ad_87a3_4aa8_baef_f4d5b3f5983a;
const struct ufsm_entry_exit entry_830247ad_87a3_4aa8_baef_f4d5b3f5983a = {
    .name = "canvas_check_text_block",
    .f = &canvas_check_text_block,
    .next = NULL,
};

/* Transitions originating from 'Transition' */
const struct ufsm_transition t_1b0a4a74_2134_4a13_aff2_f5200140f251;
const struct ufsm_guard g_4ab1a6bf_49d2_4c30_a4b4_f6f9efd2c7f6;
const struct ufsm_transition t_ad1f4d53_682f_4c7a_9f89_8b66d6a5ac4a;
const struct ufsm_guard g_488a5c67_b937_401c_a1db_3bb1987b334b;

const struct ufsm_guard g_4ab1a6bf_49d2_4c30_a4b4_f6f9efd2c7f6 = {
    .name = "canvas_transition_vertice_selected",
    .f = &canvas_transition_vertice_selected,
    .next = NULL,
};

const struct ufsm_transition t_1b0a4a74_2134_4a13_aff2_f5200140f251 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_4ab1a6bf_49d2_4c30_a4b4_f6f9efd2c7f6,
    .source = &s_71b9383e_a54c_4c13_94a9_75f5674af90f,
    .dest = &s_6fe1a397_5832_4d54_b332_afe219b0657b,
    .next = &t_ad1f4d53_682f_4c7a_9f89_8b66d6a5ac4a,
};

const struct ufsm_guard g_488a5c67_b937_401c_a1db_3bb1987b334b = {
    .name = "canvas_transition_text_block_selected",
    .f = &canvas_transition_text_block_selected,
    .next = NULL,
};

const struct ufsm_transition t_ad1f4d53_682f_4c7a_9f89_8b66d6a5ac4a = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_488a5c67_b937_401c_a1db_3bb1987b334b,
    .source = &s_71b9383e_a54c_4c13_94a9_75f5674af90f,
    .dest = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .next = NULL,
};

const struct ufsm_state s_71b9383e_a54c_4c13_94a9_75f5674af90f = {
    .index = 12,
    .name = "Transition",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_1b0a4a74_2134_4a13_aff2_f5200140f251,
    .entry = &entry_830247ad_87a3_4aa8_baef_f4d5b3f5983a,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_6fe1a397_5832_4d54_b332_afe219b0657b,
};

/* Transitions originating from 'Move vertice' */
const struct ufsm_transition t_94071954_472c_422c_a322_0a31479f1599;
const struct ufsm_action a_1fa06c3f_cac5_4d24_9aec_989b28aa07e0;

const struct ufsm_action a_1fa06c3f_cac5_4d24_9aec_989b28aa07e0 = {
    .name = "canvas_move_vertice",
    .f = &canvas_move_vertice,
    .next = NULL,
};

const struct ufsm_transition t_94071954_472c_422c_a322_0a31479f1599 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_1fa06c3f_cac5_4d24_9aec_989b28aa07e0,
    .guard = NULL,
    .source = &s_6fe1a397_5832_4d54_b332_afe219b0657b,
    .dest = &s_6fe1a397_5832_4d54_b332_afe219b0657b,
    .next = NULL,
};

const struct ufsm_state s_6fe1a397_5832_4d54_b332_afe219b0657b = {
    .index = 13,
    .name = "Move vertice",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_94071954_472c_422c_a322_0a31479f1599,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
};

/* Entry functions for state 'Text block' */
const struct ufsm_entry_exit entry_dffcc43c_1bcd_4b09_932e_5ea0e8b49814;
const struct ufsm_entry_exit entry_9401f8de_c1b6_4b76_a376_9d01332fa663;
const struct ufsm_entry_exit entry_dffcc43c_1bcd_4b09_932e_5ea0e8b49814 = {
    .name = "canvas_check_guard",
    .f = &canvas_check_guard,
    .next = &entry_9401f8de_c1b6_4b76_a376_9d01332fa663,
};

const struct ufsm_entry_exit entry_9401f8de_c1b6_4b76_a376_9d01332fa663 = {
    .name = "canvas_check_action",
    .f = &canvas_check_action,
    .next = NULL,
};

/* Transitions originating from 'Text block' */
const struct ufsm_transition t_f42275e1_7e49_40d1_88e0_df4e07040e22;
const struct ufsm_action a_54f193ba_27c6_4e56_b5e0_f4860fbb2cdf;
const struct ufsm_transition t_1056be5e_6925_4fc0_b8b1_506d7f7b5c75;
const struct ufsm_guard g_4f16985b_2a99_475b_bf3b_09dbeac17206;
const struct ufsm_transition t_86de4f6b_ab31_42c4_a75f_0711716430da;
const struct ufsm_guard g_589e02f8_8ee8_42db_b040_b357ba6b0978;
const struct ufsm_transition t_71bb64ea_43c9_4b0c_8ed3_769f2a0a0eb2;
const struct ufsm_guard g_47449948_224d_4903_968f_b1aa5ad73f22;

const struct ufsm_action a_54f193ba_27c6_4e56_b5e0_f4860fbb2cdf = {
    .name = "canvas_move_text_block",
    .f = &canvas_move_text_block,
    .next = NULL,
};

const struct ufsm_transition t_f42275e1_7e49_40d1_88e0_df4e07040e22 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_54f193ba_27c6_4e56_b5e0_f4860fbb2cdf,
    .guard = NULL,
    .source = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .dest = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .next = &t_1056be5e_6925_4fc0_b8b1_506d7f7b5c75,
};

const struct ufsm_guard g_4f16985b_2a99_475b_bf3b_09dbeac17206 = {
    .name = "canvas_action_selected",
    .f = &canvas_action_selected,
    .next = NULL,
};

const struct ufsm_transition t_1056be5e_6925_4fc0_b8b1_506d7f7b5c75 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_4f16985b_2a99_475b_bf3b_09dbeac17206,
    .source = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .dest = &s_6af64093_51b3_4564_be9a_fcb682134262,
    .next = &t_86de4f6b_ab31_42c4_a75f_0711716430da,
};

const struct ufsm_guard g_589e02f8_8ee8_42db_b040_b357ba6b0978 = {
    .name = "canvas_guard_selected",
    .f = &canvas_guard_selected,
    .next = NULL,
};

const struct ufsm_transition t_86de4f6b_ab31_42c4_a75f_0711716430da = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_589e02f8_8ee8_42db_b040_b357ba6b0978,
    .source = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .dest = &s_7921f170_0693_4d0b_bc73_b4567901a39b,
    .next = &t_71bb64ea_43c9_4b0c_8ed3_769f2a0a0eb2,
};

const struct ufsm_guard g_47449948_224d_4903_968f_b1aa5ad73f22 = {
    .name = "canvas_textblock_resize_selected",
    .f = &canvas_textblock_resize_selected,
    .next = NULL,
};

const struct ufsm_transition t_71bb64ea_43c9_4b0c_8ed3_769f2a0a0eb2 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_47449948_224d_4903_968f_b1aa5ad73f22,
    .source = &s_4b1878b4_404c_407e_8a33_4e2ef72cdae6,
    .dest = &s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb,
    .next = NULL,
};

const struct ufsm_state s_4b1878b4_404c_407e_8a33_4e2ef72cdae6 = {
    .index = 14,
    .name = "Text block",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_f42275e1_7e49_40d1_88e0_df4e07040e22,
    .entry = &entry_dffcc43c_1bcd_4b09_932e_5ea0e8b49814,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_6af64093_51b3_4564_be9a_fcb682134262,
};

/* Entry functions for state 'Guard' */
const struct ufsm_entry_exit entry_1d3740ba_6206_4de1_8eb5_2f02fe647fa2;
const struct ufsm_entry_exit entry_1d3740ba_6206_4de1_8eb5_2f02fe647fa2 = {
    .name = "canvas_focus_guard",
    .f = &canvas_focus_guard,
    .next = NULL,
};

/* Transitions originating from 'Guard' */
const struct ufsm_transition t_a985b330_a1d1_45a0_96d0_30d2b08c1e48;
const struct ufsm_action a_26349aa8_a025_44e9_b7e6_7ec4b3d83001;

const struct ufsm_action a_26349aa8_a025_44e9_b7e6_7ec4b3d83001 = {
    .name = "canvas_reorder_guard_func",
    .f = &canvas_reorder_guard_func,
    .next = NULL,
};

const struct ufsm_transition t_a985b330_a1d1_45a0_96d0_30d2b08c1e48 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_26349aa8_a025_44e9_b7e6_7ec4b3d83001,
    .guard = NULL,
    .source = &s_6af64093_51b3_4564_be9a_fcb682134262,
    .dest = &s_6af64093_51b3_4564_be9a_fcb682134262,
    .next = NULL,
};

const struct ufsm_state s_6af64093_51b3_4564_be9a_fcb682134262 = {
    .index = 15,
    .name = "Guard",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_a985b330_a1d1_45a0_96d0_30d2b08c1e48,
    .entry = &entry_1d3740ba_6206_4de1_8eb5_2f02fe647fa2,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_7921f170_0693_4d0b_bc73_b4567901a39b,
};

/* Entry functions for state 'Action' */
const struct ufsm_entry_exit entry_4f644ac5_d60d_452b_bcf1_1e076eceea32;
const struct ufsm_entry_exit entry_4f644ac5_d60d_452b_bcf1_1e076eceea32 = {
    .name = "canvas_focus_action",
    .f = &canvas_focus_action,
    .next = NULL,
};

/* Transitions originating from 'Action' */
const struct ufsm_transition t_5bd2c595_4c24_4dd0_a2f0_59dbfe8bc08f;
const struct ufsm_action a_17b54a22_897a_46d6_af7c_030a5fc83961;

const struct ufsm_action a_17b54a22_897a_46d6_af7c_030a5fc83961 = {
    .name = "canvas_reorder_action_func",
    .f = &canvas_reorder_action_func,
    .next = NULL,
};

const struct ufsm_transition t_5bd2c595_4c24_4dd0_a2f0_59dbfe8bc08f = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_17b54a22_897a_46d6_af7c_030a5fc83961,
    .guard = NULL,
    .source = &s_7921f170_0693_4d0b_bc73_b4567901a39b,
    .dest = &s_7921f170_0693_4d0b_bc73_b4567901a39b,
    .next = NULL,
};

const struct ufsm_state s_7921f170_0693_4d0b_bc73_b4567901a39b = {
    .index = 16,
    .name = "Action",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_5bd2c595_4c24_4dd0_a2f0_59dbfe8bc08f,
    .entry = &entry_4f644ac5_d60d_452b_bcf1_1e076eceea32,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_c955e985_b169_4bce_b36a_70d31da164c5,
};

/* Entry functions for state 'Exit selected' */
const struct ufsm_entry_exit entry_a6d10177_e5a7_4a5a_b3c7_78e875d504ed;
const struct ufsm_entry_exit entry_a6d10177_e5a7_4a5a_b3c7_78e875d504ed = {
    .name = "canvas_focus_exit",
    .f = &canvas_focus_exit,
    .next = NULL,
};

/* Transitions originating from 'Exit selected' */
const struct ufsm_transition t_3f2ec5a1_8d1e_4943_820b_a7ac8d0832c3;
const struct ufsm_action a_fbc928a9_cb58_414d_9eb4_ef84cd453df4;

const struct ufsm_action a_fbc928a9_cb58_414d_9eb4_ef84cd453df4 = {
    .name = "canvas_reorder_exit_func",
    .f = &canvas_reorder_exit_func,
    .next = NULL,
};

const struct ufsm_transition t_3f2ec5a1_8d1e_4943_820b_a7ac8d0832c3 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_fbc928a9_cb58_414d_9eb4_ef84cd453df4,
    .guard = NULL,
    .source = &s_c955e985_b169_4bce_b36a_70d31da164c5,
    .dest = &s_c955e985_b169_4bce_b36a_70d31da164c5,
    .next = NULL,
};

const struct ufsm_state s_c955e985_b169_4bce_b36a_70d31da164c5 = {
    .index = 17,
    .name = "Exit selected",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_3f2ec5a1_8d1e_4943_820b_a7ac8d0832c3,
    .entry = &entry_a6d10177_e5a7_4a5a_b3c7_78e875d504ed,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb,
};

/* Transitions originating from 'Resize text block' */
const struct ufsm_transition t_f30d2580_2f1f_4257_bd12_2c2f780b9029;
const struct ufsm_action a_a55ef547_954c_46da_8648_506362374f51;

const struct ufsm_action a_a55ef547_954c_46da_8648_506362374f51 = {
    .name = "canvas_resize_textblock",
    .f = &canvas_resize_textblock,
    .next = NULL,
};

const struct ufsm_transition t_f30d2580_2f1f_4257_bd12_2c2f780b9029 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_a55ef547_954c_46da_8648_506362374f51,
    .guard = NULL,
    .source = &s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb,
    .dest = &s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb,
    .next = NULL,
};

const struct ufsm_state s_df6079eb_9b1d_4ab8_9980_6eb01a8cb3fb = {
    .index = 18,
    .name = "Resize text block",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_f30d2580_2f1f_4257_bd12_2c2f780b9029,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_5bb316a6_0cd5_4fdc_99d1_f19d74c17ffd,
};

/* Entry functions for state 'Move State' */
const struct ufsm_entry_exit entry_ee0bb0aa_1621_4e2e_966d_98aeddcdf843;
const struct ufsm_entry_exit entry_ee0bb0aa_1621_4e2e_966d_98aeddcdf843 = {
    .name = "canvas_move_state_begin",
    .f = &canvas_move_state_begin,
    .next = NULL,
};

/* Exit functions for state 'Move State' */
const struct ufsm_entry_exit exit_e9c54775_5b80_4b00_b1f1_03dfa5e5bb2d;
const struct ufsm_entry_exit exit_e9c54775_5b80_4b00_b1f1_03dfa5e5bb2d = {
    .name = "canvas_move_state_end",
    .f = &canvas_move_state_end,
    .next = NULL,
};


const struct ufsm_state s_5bb316a6_0cd5_4fdc_99d1_f19d74c17ffd = {
    .index = 19,
    .name = "Move State",
    .kind = UFSM_STATE_SIMPLE,
    .transition = NULL,
    .entry = &entry_ee0bb0aa_1621_4e2e_966d_98aeddcdf843,
    .exit = &exit_e9c54775_5b80_4b00_b1f1_03dfa5e5bb2d,
    .region = &r_7cd89eb7_af2b_4a61_86ca_40bcd3a7d520,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = &s_1e103c0b_8094_4d00_831d_0e2bdc7ecf14,
};

/* Entry functions for state 'Resize state' */
const struct ufsm_entry_exit entry_b7b04605_7e8a_4310_877b_8a6e41969e34;
const struct ufsm_entry_exit entry_b7b04605_7e8a_4310_877b_8a6e41969e34 = {
    .name = "canvas_resize_region_begin",
    .f = &canvas_resize_region_begin,
    .next = NULL,
};

/* Exit functions for state 'Resize state' */
const struct ufsm_entry_exit exit_9a727306_d9cb_4a31_8204_0c234e9199b3;
const struct ufsm_entry_exit exit_9a727306_d9cb_4a31_8204_0c234e9199b3 = {
    .name = "canvas_resize_region_end",
    .f = &canvas_resize_region_end,
    .next = NULL,
};


const struct ufsm_state s_1e103c0b_8094_4d00_831d_0e2bdc7ecf14 = {
    .index = 20,
    .name = "Resize state",
    .kind = UFSM_STATE_SIMPLE,
    .transition = NULL,
    .entry = &entry_b7b04605_7e8a_4310_877b_8a6e41969e34,
    .exit = &exit_9a727306_d9cb_4a31_8204_0c234e9199b3,
    .region = &r_c089e9d0_46e3_4f36_92cc_5fc7c8cf7ab0,
    .parent_region = &r_7dc97c5b_572b_44ac_ae00_ab897e427d21,
    .next = NULL,
};

const struct ufsm_region r_c9493679_2229_4958_91a6_03288aa25eab = {
    .index = 2,
    .name = "New region",
    .has_history = false,
    .state = NULL,
    .parent_state = &s_1e103c0b_8094_4d00_831d_0e2bdc7ecf14,
    .next = NULL,
};

const struct ufsm_region r_c089e9d0_46e3_4f36_92cc_5fc7c8cf7ab0 = {
    .index = 3,
    .name = "New region",
    .has_history = false,
    .state = &s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1,
    .parent_state = &s_1e103c0b_8094_4d00_831d_0e2bdc7ecf14,
    .next = &r_c9493679_2229_4958_91a6_03288aa25eab,
};

/* Transitions originating from 'Resize region' */
const struct ufsm_transition t_9c85c251_44e9_4a43_a131_a04cdc9d4057;
const struct ufsm_action a_eb0a9e49_3785_4c03_a452_7f45f8172efd;

const struct ufsm_action a_eb0a9e49_3785_4c03_a452_7f45f8172efd = {
    .name = "canvas_resize_region",
    .f = &canvas_resize_region,
    .next = NULL,
};

const struct ufsm_transition t_9c85c251_44e9_4a43_a131_a04cdc9d4057 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_eb0a9e49_3785_4c03_a452_7f45f8172efd,
    .guard = NULL,
    .source = &s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1,
    .dest = &s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1,
    .next = NULL,
};

const struct ufsm_state s_1b2ffdbc_6a1b_4d0b_8724_087d39a819c1 = {
    .index = 21,
    .name = "Resize region",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_9c85c251_44e9_4a43_a131_a04cdc9d4057,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_c089e9d0_46e3_4f36_92cc_5fc7c8cf7ab0,
    .next = NULL,
};

const struct ufsm_region r_7cd89eb7_af2b_4a61_86ca_40bcd3a7d520 = {
    .index = 4,
    .name = "New region",
    .has_history = false,
    .state = &s_50565759_c7e0_426f_948e_1cbc276a1204,
    .parent_state = &s_5bb316a6_0cd5_4fdc_99d1_f19d74c17ffd,
    .next = NULL,
};

/* Transitions originating from 'Move State' */
const struct ufsm_transition t_f10bfc6c_4000_40a2_b10b_bfeffc5ba21c;
const struct ufsm_action a_6918dc69_c703_45d0_b52f_b3f1f61807c7;

const struct ufsm_action a_6918dc69_c703_45d0_b52f_b3f1f61807c7 = {
    .name = "canvas_move_state",
    .f = &canvas_move_state,
    .next = NULL,
};

const struct ufsm_transition t_f10bfc6c_4000_40a2_b10b_bfeffc5ba21c = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_6918dc69_c703_45d0_b52f_b3f1f61807c7,
    .guard = NULL,
    .source = &s_50565759_c7e0_426f_948e_1cbc276a1204,
    .dest = &s_50565759_c7e0_426f_948e_1cbc276a1204,
    .next = NULL,
};

const struct ufsm_state s_50565759_c7e0_426f_948e_1cbc276a1204 = {
    .index = 22,
    .name = "Move State",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_f10bfc6c_4000_40a2_b10b_bfeffc5ba21c,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_7cd89eb7_af2b_4a61_86ca_40bcd3a7d520,
    .next = NULL,
};

const struct ufsm_region r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2 = {
    .index = 5,
    .name = "Tool controller",
    .has_history = false,
    .state = &s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c,
    .parent_state = &s_9bc407ce_cf13_4456_b060_9742ec032659,
    .next = NULL,
};

/* Transitions originating from 'Tool' */
const struct ufsm_transition t_2236ab27_d1c1_4e72_a96b_8def20d1e876;
const struct ufsm_guard g_a15894db_35da_4c09_b7e3_25b70758652e;
const struct ufsm_transition t_ec4c65ed_f79d_49dc_b5df_58c3b7306025;
const struct ufsm_guard g_06a340df_8018_4dfe_9457_f3a1b43417d7;
const struct ufsm_transition t_fc8b90d7_a4bb_4278_a8a0_c84f0aa42f2a;
const struct ufsm_guard g_a263c4eb_31ee_466f_bda2_000a32d9f979;

const struct ufsm_guard g_a15894db_35da_4c09_b7e3_25b70758652e = {
    .name = "canvas_state_selected",
    .f = &canvas_state_selected,
    .next = NULL,
};

const struct ufsm_transition t_2236ab27_d1c1_4e72_a96b_8def20d1e876 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_a15894db_35da_4c09_b7e3_25b70758652e,
    .source = &s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c,
    .dest = &s_411c1230_4754_443b_90d6_f2c471efe170,
    .next = &t_ec4c65ed_f79d_49dc_b5df_58c3b7306025,
};

const struct ufsm_guard g_06a340df_8018_4dfe_9457_f3a1b43417d7 = {
    .name = "canvas_region_selected",
    .f = &canvas_region_selected,
    .next = NULL,
};

const struct ufsm_transition t_ec4c65ed_f79d_49dc_b5df_58c3b7306025 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_06a340df_8018_4dfe_9457_f3a1b43417d7,
    .source = &s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c,
    .dest = &s_ad9bbeee_0628_402e_92dd_684a4a35de9b,
    .next = &t_fc8b90d7_a4bb_4278_a8a0_c84f0aa42f2a,
};

const struct ufsm_guard g_a263c4eb_31ee_466f_bda2_000a32d9f979 = {
    .name = "canvas_transition_selected",
    .f = &canvas_transition_selected,
    .next = NULL,
};

const struct ufsm_transition t_fc8b90d7_a4bb_4278_a8a0_c84f0aa42f2a = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = &g_a263c4eb_31ee_466f_bda2_000a32d9f979,
    .source = &s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c,
    .dest = &s_20cef1d5_aa6d_4418_a109_833bad1003d2,
    .next = NULL,
};

const struct ufsm_state s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c = {
    .index = 23,
    .name = "Tool",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_2236ab27_d1c1_4e72_a96b_8def20d1e876,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_ab4fecb3_a182_4199_b3c9_32a4d900ee28,
};

/* Transitions originating from 'Init' */
const struct ufsm_transition t_a135a2b8_c113_429c_96f6_6fcdc023a643;

const struct ufsm_transition t_a135a2b8_c113_429c_96f6_6fcdc023a643 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_ab4fecb3_a182_4199_b3c9_32a4d900ee28,
    .dest = &s_a5772b8e_a642_4ba1_9ba7_c2059b27f14c,
    .next = NULL,
};

const struct ufsm_state s_ab4fecb3_a182_4199_b3c9_32a4d900ee28 = {
    .index = 24,
    .name = "Init",
    .kind = UFSM_STATE_INIT,
    .transition = &t_a135a2b8_c113_429c_96f6_6fcdc023a643,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_411c1230_4754_443b_90d6_f2c471efe170,
};

/* Transitions originating from 'State' */
const struct ufsm_transition t_e5e6efb3_98e1_4ddc_bb84_27b8b211fed7;

const struct ufsm_transition t_e5e6efb3_98e1_4ddc_bb84_27b8b211fed7 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_411c1230_4754_443b_90d6_f2c471efe170,
    .dest = &s_9b32f09f_6ffc_4587_ba5e_82f3ea05b4f3,
    .next = NULL,
};

const struct ufsm_state s_411c1230_4754_443b_90d6_f2c471efe170 = {
    .index = 25,
    .name = "State",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_e5e6efb3_98e1_4ddc_bb84_27b8b211fed7,
    .entry = NULL,
    .exit = NULL,
    .region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_ad9bbeee_0628_402e_92dd_684a4a35de9b,
};

/* Transitions originating from 'Region' */
const struct ufsm_transition t_5a4234e3_9ae3_4643_a0b1_deeb8212e0c2;

const struct ufsm_transition t_5a4234e3_9ae3_4643_a0b1_deeb8212e0c2 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_ad9bbeee_0628_402e_92dd_684a4a35de9b,
    .dest = &s_80904f43_c8d8_42fd_b771_3b62987f92d3,
    .next = NULL,
};

const struct ufsm_state s_ad9bbeee_0628_402e_92dd_684a4a35de9b = {
    .index = 26,
    .name = "Region",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_5a4234e3_9ae3_4643_a0b1_deeb8212e0c2,
    .entry = NULL,
    .exit = NULL,
    .region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_20cef1d5_aa6d_4418_a109_833bad1003d2,
};

/* Transitions originating from 'Transition' */
const struct ufsm_transition t_f8a9f9e2_9945_4d4f_9b99_18f5a660bad5;

const struct ufsm_transition t_f8a9f9e2_9945_4d4f_9b99_18f5a660bad5 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_20cef1d5_aa6d_4418_a109_833bad1003d2,
    .dest = &s_0a4d49d9_c0ce_45ff_aa6a_81f95e9e98fc,
    .next = NULL,
};

const struct ufsm_state s_20cef1d5_aa6d_4418_a109_833bad1003d2 = {
    .index = 27,
    .name = "Transition",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_f8a9f9e2_9945_4d4f_9b99_18f5a660bad5,
    .entry = NULL,
    .exit = NULL,
    .region = &r_b31f9254_ea60_4f9d_bfd5_3780fab7dde3,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_9b32f09f_6ffc_4587_ba5e_82f3ea05b4f3,
};


const struct ufsm_state s_9b32f09f_6ffc_4587_ba5e_82f3ea05b4f3 = {
    .index = 28,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_80904f43_c8d8_42fd_b771_3b62987f92d3,
};


const struct ufsm_state s_80904f43_c8d8_42fd_b771_3b62987f92d3 = {
    .index = 29,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = &s_0a4d49d9_c0ce_45ff_aa6a_81f95e9e98fc,
};


const struct ufsm_state s_0a4d49d9_c0ce_45ff_aa6a_81f95e9e98fc = {
    .index = 30,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_73c8002b_fc21_4c2c_b0f8_34c1375ffad2,
    .next = NULL,
};

const struct ufsm_region r_b31f9254_ea60_4f9d_bfd5_3780fab7dde3 = {
    .index = 6,
    .name = "Transition tools",
    .has_history = false,
    .state = NULL,
    .parent_state = &s_20cef1d5_aa6d_4418_a109_833bad1003d2,
    .next = NULL,
};

const struct ufsm_region r_1875929f_f938_4a5b_a695_e6a578848da0 = {
    .index = 7,
    .name = "Region tools",
    .has_history = false,
    .state = &s_afb7a57a_f268_49d7_8834_3955d80f534c,
    .parent_state = &s_ad9bbeee_0628_402e_92dd_684a4a35de9b,
    .next = NULL,
};

/* Transitions originating from 'Init' */
const struct ufsm_transition t_afc10218_e2a9_4917_b536_5b3f74e4b84e;

const struct ufsm_transition t_afc10218_e2a9_4917_b536_5b3f74e4b84e = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_afb7a57a_f268_49d7_8834_3955d80f534c,
    .dest = &s_51ff5faa_b548_4b41_b3eb_1576932e9fe7,
    .next = NULL,
};

const struct ufsm_state s_afb7a57a_f268_49d7_8834_3955d80f534c = {
    .index = 31,
    .name = "Init",
    .kind = UFSM_STATE_INIT,
    .transition = &t_afc10218_e2a9_4917_b536_5b3f74e4b84e,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_51ff5faa_b548_4b41_b3eb_1576932e9fe7,
};

/* Transitions originating from 'Region tools' */
const struct ufsm_transition t_8d13b950_08f0_4a8b_9304_0e4451d11f7f;
const struct ufsm_transition t_1d1a3c07_4ac5_43c1_a78f_9acd2fc3c911;
const struct ufsm_action a_bd3cd067_12ad_477e_b047_e36dfbc3c52a;

const struct ufsm_transition t_8d13b950_08f0_4a8b_9304_0e4451d11f7f = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_a5bd1392_5461_489e_ad96_12bec38ed212,
    .action = NULL,
    .guard = NULL,
    .source = &s_51ff5faa_b548_4b41_b3eb_1576932e9fe7,
    .dest = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
    .next = &t_1d1a3c07_4ac5_43c1_a78f_9acd2fc3c911,
};

const struct ufsm_action a_bd3cd067_12ad_477e_b047_e36dfbc3c52a = {
    .name = "canvas_save",
    .f = &canvas_save,
    .next = NULL,
};

const struct ufsm_transition t_1d1a3c07_4ac5_43c1_a78f_9acd2fc3c911 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_8026ece2_dd00_44e8_8613_a68197aaec7c,
    .action = &a_bd3cd067_12ad_477e_b047_e36dfbc3c52a,
    .guard = NULL,
    .source = &s_51ff5faa_b548_4b41_b3eb_1576932e9fe7,
    .dest = &s_a3597828_1b7e_4269_ba3a_1c77e960c864,
    .next = NULL,
};

const struct ufsm_state s_51ff5faa_b548_4b41_b3eb_1576932e9fe7 = {
    .index = 32,
    .name = "Region tools",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_8d13b950_08f0_4a8b_9304_0e4451d11f7f,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
};

/* Transitions originating from 'Add' */
const struct ufsm_transition t_2164f156_98bb_407f_8c0a_847be7458a49;
const struct ufsm_transition t_2c3f3617_b549_4c5c_bb11_e09289e06e6c;
const struct ufsm_transition t_89301021_c37c_471f_9519_109ebe6b9279;
const struct ufsm_action a_89ec3eeb_3329_45f8_9a5b_a6abd25629d5;
const struct ufsm_transition t_3fb4e833_40b4_4c00_9194_2c31895aad58;
const struct ufsm_action a_30af2f21_7f3f_4fac_858c_bb50b7e773fa;

const struct ufsm_transition t_2164f156_98bb_407f_8c0a_847be7458a49 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_8026ece2_dd00_44e8_8613_a68197aaec7c,
    .action = NULL,
    .guard = NULL,
    .source = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
    .dest = &s_579a57b9_4811_47b4_bcb3_e29e3d5bfbd0,
    .next = &t_2c3f3617_b549_4c5c_bb11_e09289e06e6c,
};

const struct ufsm_transition t_2c3f3617_b549_4c5c_bb11_e09289e06e6c = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_2dcc8a3e_f0b8_4e8a_96a0_a339f4dc3bfb,
    .action = NULL,
    .guard = NULL,
    .source = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
    .dest = &s_0aba8ad4_38a9_4738_9804_0ea11c158a5b,
    .next = &t_89301021_c37c_471f_9519_109ebe6b9279,
};

const struct ufsm_action a_89ec3eeb_3329_45f8_9a5b_a6abd25629d5 = {
    .name = "canvas_create_init_state",
    .f = &canvas_create_init_state,
    .next = NULL,
};

const struct ufsm_transition t_89301021_c37c_471f_9519_109ebe6b9279 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_312affef_dc71_4190_93b8_b8b3f2623d71,
    .action = &a_89ec3eeb_3329_45f8_9a5b_a6abd25629d5,
    .guard = NULL,
    .source = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
    .dest = &s_9e7cfc8f_eaad_49e7_af0c_62ef54a95902,
    .next = &t_3fb4e833_40b4_4c00_9194_2c31895aad58,
};

const struct ufsm_action a_30af2f21_7f3f_4fac_858c_bb50b7e773fa = {
    .name = "canvas_create_final_state",
    .f = &canvas_create_final_state,
    .next = NULL,
};

const struct ufsm_transition t_3fb4e833_40b4_4c00_9194_2c31895aad58 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_5436ff7d_0fcb_4cfb_bd94_e82f14913849,
    .action = &a_30af2f21_7f3f_4fac_858c_bb50b7e773fa,
    .guard = NULL,
    .source = &s_09ed5b3c_d326_46bc_8ae1_f1377e942207,
    .dest = &s_251f5542_7682_4cbb_bcdf_658d352b4ac7,
    .next = NULL,
};

const struct ufsm_state s_09ed5b3c_d326_46bc_8ae1_f1377e942207 = {
    .index = 33,
    .name = "Add",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_2164f156_98bb_407f_8c0a_847be7458a49,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_981f9378_69f5_43fe_b5dc_9d20146f8512,
};

/* Exit functions for state 'New state' */
const struct ufsm_entry_exit exit_f81544f9_c8bf_4338_b016_265eb5ca6d73;
const struct ufsm_entry_exit exit_f81544f9_c8bf_4338_b016_265eb5ca6d73 = {
    .name = "canvas_hide_state_hint",
    .f = &canvas_hide_state_hint,
    .next = NULL,
};


const struct ufsm_state s_981f9378_69f5_43fe_b5dc_9d20146f8512 = {
    .index = 34,
    .name = "New state",
    .kind = UFSM_STATE_SIMPLE,
    .transition = NULL,
    .entry = NULL,
    .exit = &exit_f81544f9_c8bf_4338_b016_265eb5ca6d73,
    .region = &r_a50feb78_b194_4729_bfcf_65232ca6637f,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_de4a6839_98a3_4ad2_b3e8_afd201ff2526,
};


const struct ufsm_state s_de4a6839_98a3_4ad2_b3e8_afd201ff2526 = {
    .index = 35,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_5577a77a_a350_4e46_b546_d8e30a5a4218,
};

/* Exit functions for state 'New transition' */
const struct ufsm_entry_exit exit_ef406f02_bf16_48ff_bc41_0b9439965f70;
const struct ufsm_entry_exit exit_fb14b1ed_ed67_462b_a08d_6ca461999586;
const struct ufsm_entry_exit exit_ef406f02_bf16_48ff_bc41_0b9439965f70 = {
    .name = "canvas_hide_transition_hint",
    .f = &canvas_hide_transition_hint,
    .next = &exit_fb14b1ed_ed67_462b_a08d_6ca461999586,
};

const struct ufsm_entry_exit exit_fb14b1ed_ed67_462b_a08d_6ca461999586 = {
    .name = "canvas_cleanup_transition",
    .f = &canvas_cleanup_transition,
    .next = NULL,
};

/* Transitions originating from 'New transition' */
const struct ufsm_transition t_37ba5277_6ab7_4a89_aa5c_c86356d2d835;

const struct ufsm_transition t_37ba5277_6ab7_4a89_aa5c_c86356d2d835 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_5577a77a_a350_4e46_b546_d8e30a5a4218,
    .dest = &s_61e6d20a_06ae_484d_b503_b553a57076fb,
    .next = NULL,
};

const struct ufsm_state s_5577a77a_a350_4e46_b546_d8e30a5a4218 = {
    .index = 36,
    .name = "New transition",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_37ba5277_6ab7_4a89_aa5c_c86356d2d835,
    .entry = NULL,
    .exit = &exit_ef406f02_bf16_48ff_bc41_0b9439965f70,
    .region = &r_399603a6_1dcf_4977_9a02_948ace6516e8,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_61e6d20a_06ae_484d_b503_b553a57076fb,
};


const struct ufsm_state s_61e6d20a_06ae_484d_b503_b553a57076fb = {
    .index = 37,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_9e7cfc8f_eaad_49e7_af0c_62ef54a95902,
};


const struct ufsm_state s_9e7cfc8f_eaad_49e7_af0c_62ef54a95902 = {
    .index = 38,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_251f5542_7682_4cbb_bcdf_658d352b4ac7,
};


const struct ufsm_state s_251f5542_7682_4cbb_bcdf_658d352b4ac7 = {
    .index = 39,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = &s_a3597828_1b7e_4269_ba3a_1c77e960c864,
};


const struct ufsm_state s_a3597828_1b7e_4269_ba3a_1c77e960c864 = {
    .index = 40,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_1875929f_f938_4a5b_a695_e6a578848da0,
    .next = NULL,
};

const struct ufsm_region r_399603a6_1dcf_4977_9a02_948ace6516e8 = {
    .index = 8,
    .name = "New region",
    .has_history = false,
    .state = &s_0aba8ad4_38a9_4738_9804_0ea11c158a5b,
    .parent_state = &s_5577a77a_a350_4e46_b546_d8e30a5a4218,
    .next = NULL,
};

/* Transitions originating from 'Start' */
const struct ufsm_transition t_26cd65f2_5b3c_4b6a_972e_4c373f725c31;
const struct ufsm_action a_d195f7c4_cd2c_41b4_b90e_83b456687c4a;
const struct ufsm_action a_b46205db_54a3_4478_8a8c_1184a008a035;

const struct ufsm_action a_d195f7c4_cd2c_41b4_b90e_83b456687c4a = {
    .name = "canvas_create_transition_start",
    .f = &canvas_create_transition_start,
    .next = &a_b46205db_54a3_4478_8a8c_1184a008a035,
};

const struct ufsm_action a_b46205db_54a3_4478_8a8c_1184a008a035 = {
    .name = "canvas_update_transition_hint",
    .f = &canvas_update_transition_hint,
    .next = NULL,
};

const struct ufsm_transition t_26cd65f2_5b3c_4b6a_972e_4c373f725c31 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = &a_d195f7c4_cd2c_41b4_b90e_83b456687c4a,
    .guard = NULL,
    .source = &s_0aba8ad4_38a9_4738_9804_0ea11c158a5b,
    .dest = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .next = NULL,
};

const struct ufsm_state s_0aba8ad4_38a9_4738_9804_0ea11c158a5b = {
    .index = 41,
    .name = "Start",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_26cd65f2_5b3c_4b6a_972e_4c373f725c31,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_399603a6_1dcf_4977_9a02_948ace6516e8,
    .next = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
};

/* Transitions originating from 'End' */
const struct ufsm_transition t_75bf6d51_b12a_4965_88af_8322eed7532b;
const struct ufsm_action a_a85611d6_acab_4773_ab56_2fda4974fafb;
const struct ufsm_action a_092993f7_516b_41f5_8251_a721f344944a;
const struct ufsm_transition t_8609c347_f4e1_43fd_a799_5ea3d33d3491;
const struct ufsm_transition t_64d6ffc5_cd5f_421b_94d9_6f492e0d4d95;
const struct ufsm_action a_3c18613e_bd66_4136_aedc_f696012bbd48;

const struct ufsm_action a_a85611d6_acab_4773_ab56_2fda4974fafb = {
    .name = "canvas_transition_vdel_last",
    .f = &canvas_transition_vdel_last,
    .next = &a_092993f7_516b_41f5_8251_a721f344944a,
};

const struct ufsm_action a_092993f7_516b_41f5_8251_a721f344944a = {
    .name = "canvas_update_transition_hint",
    .f = &canvas_update_transition_hint,
    .next = NULL,
};

const struct ufsm_transition t_75bf6d51_b12a_4965_88af_8322eed7532b = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_ff3ba5c8_93e8_430e_b37a_8196a4be36fa,
    .action = &a_a85611d6_acab_4773_ab56_2fda4974fafb,
    .guard = NULL,
    .source = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .dest = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .next = &t_8609c347_f4e1_43fd_a799_5ea3d33d3491,
};

const struct ufsm_transition t_8609c347_f4e1_43fd_a799_5ea3d33d3491 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_aa3e0691_1994_453b_b506_d9e2400ca6d9,
    .action = NULL,
    .guard = NULL,
    .source = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .dest = &s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41,
    .next = &t_64d6ffc5_cd5f_421b_94d9_6f492e0d4d95,
};

const struct ufsm_action a_3c18613e_bd66_4136_aedc_f696012bbd48 = {
    .name = "canvas_create_transition",
    .f = &canvas_create_transition,
    .next = NULL,
};

const struct ufsm_transition t_64d6ffc5_cd5f_421b_94d9_6f492e0d4d95 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = &a_3c18613e_bd66_4136_aedc_f696012bbd48,
    .guard = NULL,
    .source = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .dest = &s_4bc349e7_ed14_49e2_a5c6_5e279183799f,
    .next = NULL,
};

const struct ufsm_state s_fc6399d1_c9b5_4a38_88d7_755d83db66e7 = {
    .index = 42,
    .name = "End",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_75bf6d51_b12a_4965_88af_8322eed7532b,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_399603a6_1dcf_4977_9a02_948ace6516e8,
    .next = &s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41,
};

/* Transitions originating from 'Vertice' */
const struct ufsm_transition t_e069b40c_5f7b_41b5_84b4_0a0c7b19b0df;
const struct ufsm_transition t_b0bd24ef_27bd_46c6_9d1d_f086fbe9a48c;
const struct ufsm_action a_efabebbd_1be5_4078_882c_59d71c084ed0;

const struct ufsm_transition t_e069b40c_5f7b_41b5_84b4_0a0c7b19b0df = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_477900d8_124e_45b9_99d9_4e2aca45fe1d,
    .action = NULL,
    .guard = NULL,
    .source = &s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41,
    .dest = &s_fc6399d1_c9b5_4a38_88d7_755d83db66e7,
    .next = &t_b0bd24ef_27bd_46c6_9d1d_f086fbe9a48c,
};

const struct ufsm_action a_efabebbd_1be5_4078_882c_59d71c084ed0 = {
    .name = "canvas_add_transition_vertice",
    .f = &canvas_add_transition_vertice,
    .next = NULL,
};

const struct ufsm_transition t_b0bd24ef_27bd_46c6_9d1d_f086fbe9a48c = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = &a_efabebbd_1be5_4078_882c_59d71c084ed0,
    .guard = NULL,
    .source = &s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41,
    .dest = &s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41,
    .next = NULL,
};

const struct ufsm_state s_643d909a_46c4_48b9_83ec_e5aa2bfcbc41 = {
    .index = 43,
    .name = "Vertice",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_e069b40c_5f7b_41b5_84b4_0a0c7b19b0df,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_399603a6_1dcf_4977_9a02_948ace6516e8,
    .next = &s_4bc349e7_ed14_49e2_a5c6_5e279183799f,
};


const struct ufsm_state s_4bc349e7_ed14_49e2_a5c6_5e279183799f = {
    .index = 44,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_399603a6_1dcf_4977_9a02_948ace6516e8,
    .next = NULL,
};

const struct ufsm_region r_a50feb78_b194_4729_bfcf_65232ca6637f = {
    .index = 9,
    .name = "New region",
    .has_history = false,
    .state = &s_579a57b9_4811_47b4_bcb3_e29e3d5bfbd0,
    .parent_state = &s_981f9378_69f5_43fe_b5dc_9d20146f8512,
    .next = NULL,
};

/* Transitions originating from 'Start' */
const struct ufsm_transition t_59129edf_e5c4_4e73_af4c_6fd92261070c;
const struct ufsm_action a_de8381e2_6284_4ded_966c_384b3ece0627;
const struct ufsm_action a_c4b0b094_991b_4b57_b0e1_b99f66f406c5;

const struct ufsm_action a_de8381e2_6284_4ded_966c_384b3ece0627 = {
    .name = "canvas_new_state_set_scoords",
    .f = &canvas_new_state_set_scoords,
    .next = &a_c4b0b094_991b_4b57_b0e1_b99f66f406c5,
};

const struct ufsm_action a_c4b0b094_991b_4b57_b0e1_b99f66f406c5 = {
    .name = "canvas_show_state_hint",
    .f = &canvas_show_state_hint,
    .next = NULL,
};

const struct ufsm_transition t_59129edf_e5c4_4e73_af4c_6fd92261070c = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = &a_de8381e2_6284_4ded_966c_384b3ece0627,
    .guard = NULL,
    .source = &s_579a57b9_4811_47b4_bcb3_e29e3d5bfbd0,
    .dest = &s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc,
    .next = NULL,
};

const struct ufsm_state s_579a57b9_4811_47b4_bcb3_e29e3d5bfbd0 = {
    .index = 45,
    .name = "Start",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_59129edf_e5c4_4e73_af4c_6fd92261070c,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_a50feb78_b194_4729_bfcf_65232ca6637f,
    .next = &s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc,
};

/* Transitions originating from 'End' */
const struct ufsm_transition t_3bbe2091_6c8b_4e30_a60a_a78f3ebd9b09;
const struct ufsm_action a_fe15cd35_324a_4763_87db_adcac9e4e25b;
const struct ufsm_transition t_d2bb4846_d816_476c_97c3_184577aa2b8f;
const struct ufsm_action a_9a20ca43_b9b7_4553_bdb5_6134d4b2477c;

const struct ufsm_action a_fe15cd35_324a_4763_87db_adcac9e4e25b = {
    .name = "canvas_create_new_state",
    .f = &canvas_create_new_state,
    .next = NULL,
};

const struct ufsm_transition t_3bbe2091_6c8b_4e30_a60a_a78f3ebd9b09 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_147c056e_9041_4a99_bad7_c5c25b13104a,
    .action = &a_fe15cd35_324a_4763_87db_adcac9e4e25b,
    .guard = NULL,
    .source = &s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc,
    .dest = &s_de4a6839_98a3_4ad2_b3e8_afd201ff2526,
    .next = &t_d2bb4846_d816_476c_97c3_184577aa2b8f,
};

const struct ufsm_action a_9a20ca43_b9b7_4553_bdb5_6134d4b2477c = {
    .name = "canvas_update_state_hint",
    .f = &canvas_update_state_hint,
    .next = NULL,
};

const struct ufsm_transition t_d2bb4846_d816_476c_97c3_184577aa2b8f = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_060051ac_b9c7_4b85_b478_dcdf54362f21,
    .action = &a_9a20ca43_b9b7_4553_bdb5_6134d4b2477c,
    .guard = NULL,
    .source = &s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc,
    .dest = &s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc,
    .next = NULL,
};

const struct ufsm_state s_3eae6205_4dc7_43c7_b9e0_ea2f8efadafc = {
    .index = 46,
    .name = "End",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_3bbe2091_6c8b_4e30_a60a_a78f3ebd9b09,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_a50feb78_b194_4729_bfcf_65232ca6637f,
    .next = NULL,
};

const struct ufsm_region r_f38bf7dc_626b_47b8_bafa_50a13beea4e2 = {
    .index = 10,
    .name = "State tools",
    .has_history = false,
    .state = &s_ee8b0968_9dd9_4249_bdc8_cfb8795dc5d8,
    .parent_state = &s_411c1230_4754_443b_90d6_f2c471efe170,
    .next = NULL,
};

/* Transitions originating from 'Init' */
const struct ufsm_transition t_46e6de4f_7811_4a5b_a6dd_6d8602ba7649;

const struct ufsm_transition t_46e6de4f_7811_4a5b_a6dd_6d8602ba7649 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = NULL,
    .guard = NULL,
    .source = &s_ee8b0968_9dd9_4249_bdc8_cfb8795dc5d8,
    .dest = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .next = NULL,
};

const struct ufsm_state s_ee8b0968_9dd9_4249_bdc8_cfb8795dc5d8 = {
    .index = 47,
    .name = "Init",
    .kind = UFSM_STATE_INIT,
    .transition = &t_46e6de4f_7811_4a5b_a6dd_6d8602ba7649,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
};

/* Transitions originating from 'State tools' */
const struct ufsm_transition t_d0f1f748_3041_4a61_b544_c50f04d0c1c4;
const struct ufsm_transition t_60e95b7f_92e2_4a79_8a36_2dcfc82f5e50;
const struct ufsm_transition t_ce0fef3a_170e_4f4f_a393_204e3858c751;
const struct ufsm_action a_27d7e2eb_08c9_4e75_ae8c_72fa2b14d50a;
const struct ufsm_transition t_a1459f99_7543_45cc_ac90_1cd1c5d1140e;

const struct ufsm_transition t_d0f1f748_3041_4a61_b544_c50f04d0c1c4 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_a5bd1392_5461_489e_ad96_12bec38ed212,
    .action = NULL,
    .guard = NULL,
    .source = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .dest = &s_d00443ac_2597_4673_82b0_e9b6349e5700,
    .next = &t_60e95b7f_92e2_4a79_8a36_2dcfc82f5e50,
};

const struct ufsm_transition t_60e95b7f_92e2_4a79_8a36_2dcfc82f5e50 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_93f84b98_6e9e_4acb_8011_6c758d37ba1b,
    .action = NULL,
    .guard = NULL,
    .source = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .dest = &s_9dcc0d0a_9027_433a_98a9_6484ee801210,
    .next = &t_ce0fef3a_170e_4f4f_a393_204e3858c751,
};

const struct ufsm_action a_27d7e2eb_08c9_4e75_ae8c_72fa2b14d50a = {
    .name = "canvas_translate_state",
    .f = &canvas_translate_state,
    .next = NULL,
};

const struct ufsm_transition t_ce0fef3a_170e_4f4f_a393_204e3858c751 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_abdf4bb1_e569_4bc1_b984_8b08b5366cf4,
    .action = &a_27d7e2eb_08c9_4e75_ae8c_72fa2b14d50a,
    .guard = NULL,
    .source = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .dest = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .next = &t_a1459f99_7543_45cc_ac90_1cd1c5d1140e,
};

const struct ufsm_transition t_a1459f99_7543_45cc_ac90_1cd1c5d1140e = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_94c4dde3_d5b5_44ea_82ec_9e8b55e37892,
    .action = NULL,
    .guard = NULL,
    .source = &s_960d3c90_38ca_4b40_ba58_3fa52185d2c2,
    .dest = &s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2,
    .next = NULL,
};

const struct ufsm_state s_960d3c90_38ca_4b40_ba58_3fa52185d2c2 = {
    .index = 48,
    .name = "State tools",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_d0f1f748_3041_4a61_b544_c50f04d0c1c4,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_d5563896_3314_42c4_af48_de144f157b2e,
};


const struct ufsm_state s_d5563896_3314_42c4_af48_de144f157b2e = {
    .index = 49,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_ed5c60cd_007c_45e9_bbf2_b28b9bee2f65,
};


const struct ufsm_state s_ed5c60cd_007c_45e9_bbf2_b28b9bee2f65 = {
    .index = 50,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_79b42026_e0d8_4aea_bf1b_b131d28f76c2,
};


const struct ufsm_state s_79b42026_e0d8_4aea_bf1b_b131d28f76c2 = {
    .index = 51,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_4f8688ed_1d77_4105_a8c3_32d2a01b4323,
};


const struct ufsm_state s_4f8688ed_1d77_4105_a8c3_32d2a01b4323 = {
    .index = 52,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_d00443ac_2597_4673_82b0_e9b6349e5700,
};

/* Transitions originating from 'Add' */
const struct ufsm_transition t_5df44fb0_3e60_4696_a28f_231b349e715b;
const struct ufsm_action a_0222a355_0e6d_491c_adfb_1ee421385ebe;
const struct ufsm_transition t_f4a49ef2_816c_4f06_a62b_636ee7a4dcde;
const struct ufsm_action a_e7ac0279_26ce_42f1_907b_c6c79bc5ed17;
const struct ufsm_transition t_e36cfa2f_65fa_411d_9052_814066a2515d;
const struct ufsm_action a_c2ec4bfc_819c_4827_9fc6_09b867dcb484;

const struct ufsm_action a_0222a355_0e6d_491c_adfb_1ee421385ebe = {
    .name = "canvas_add_region",
    .f = &canvas_add_region,
    .next = NULL,
};

const struct ufsm_transition t_5df44fb0_3e60_4696_a28f_231b349e715b = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_faf24206_d5cc_4593_8f94_2951717e6154,
    .action = &a_0222a355_0e6d_491c_adfb_1ee421385ebe,
    .guard = NULL,
    .source = &s_d00443ac_2597_4673_82b0_e9b6349e5700,
    .dest = &s_d5563896_3314_42c4_af48_de144f157b2e,
    .next = &t_f4a49ef2_816c_4f06_a62b_636ee7a4dcde,
};

const struct ufsm_action a_e7ac0279_26ce_42f1_907b_c6c79bc5ed17 = {
    .name = "canvas_add_entry",
    .f = &canvas_add_entry,
    .next = NULL,
};

const struct ufsm_transition t_f4a49ef2_816c_4f06_a62b_636ee7a4dcde = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_93f84b98_6e9e_4acb_8011_6c758d37ba1b,
    .action = &a_e7ac0279_26ce_42f1_907b_c6c79bc5ed17,
    .guard = NULL,
    .source = &s_d00443ac_2597_4673_82b0_e9b6349e5700,
    .dest = &s_ed5c60cd_007c_45e9_bbf2_b28b9bee2f65,
    .next = &t_e36cfa2f_65fa_411d_9052_814066a2515d,
};

const struct ufsm_action a_c2ec4bfc_819c_4827_9fc6_09b867dcb484 = {
    .name = "canvas_add_exit",
    .f = &canvas_add_exit,
    .next = NULL,
};

const struct ufsm_transition t_e36cfa2f_65fa_411d_9052_814066a2515d = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = &trigger_6153e3ce_a758_469e_b559_b8f06b691d7a,
    .action = &a_c2ec4bfc_819c_4827_9fc6_09b867dcb484,
    .guard = NULL,
    .source = &s_d00443ac_2597_4673_82b0_e9b6349e5700,
    .dest = &s_79b42026_e0d8_4aea_bf1b_b131d28f76c2,
    .next = NULL,
};

const struct ufsm_state s_d00443ac_2597_4673_82b0_e9b6349e5700 = {
    .index = 53,
    .name = "Add",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_5df44fb0_3e60_4696_a28f_231b349e715b,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_9dcc0d0a_9027_433a_98a9_6484ee801210,
};

/* Transitions originating from 'Edit' */
const struct ufsm_transition t_5eab8cc6_a546_4d54_8ce1_17ae54205b61;
const struct ufsm_action a_16b8748a_5df8_4271_a01f_23f63429a579;
const struct ufsm_guard g_4d827bdb_c798_4829_93c4_90acd8a35d02;
const struct ufsm_transition t_920a29b7_5375_466c_ac35_9c3a6735d0da;
const struct ufsm_action a_c9138d12_f221_4866_863c_0332ab591df9;
const struct ufsm_guard g_dbc3dc53_429b_4f24_bac5_d7bd9aeb78dc;
const struct ufsm_transition t_8313a454_c083_40eb_a201_b253c3fc2da4;
const struct ufsm_action a_86e9ffb9_8c7f_4d5b_ba2e_f51c1f47b6aa;

const struct ufsm_action a_16b8748a_5df8_4271_a01f_23f63429a579 = {
    .name = "canvas_edit_state_entry",
    .f = &canvas_edit_state_entry,
    .next = NULL,
};

const struct ufsm_guard g_4d827bdb_c798_4829_93c4_90acd8a35d02 = {
    .name = "canvas_state_entry_selected",
    .f = &canvas_state_entry_selected,
    .next = NULL,
};

const struct ufsm_transition t_5eab8cc6_a546_4d54_8ce1_17ae54205b61 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_16b8748a_5df8_4271_a01f_23f63429a579,
    .guard = &g_4d827bdb_c798_4829_93c4_90acd8a35d02,
    .source = &s_9dcc0d0a_9027_433a_98a9_6484ee801210,
    .dest = &s_57bf38bf_9f31_452c_ae58_04890f81958a,
    .next = &t_920a29b7_5375_466c_ac35_9c3a6735d0da,
};

const struct ufsm_action a_c9138d12_f221_4866_863c_0332ab591df9 = {
    .name = "canvas_edit_state_exit",
    .f = &canvas_edit_state_exit,
    .next = NULL,
};

const struct ufsm_guard g_dbc3dc53_429b_4f24_bac5_d7bd9aeb78dc = {
    .name = "canvas_state_exit_selected",
    .f = &canvas_state_exit_selected,
    .next = NULL,
};

const struct ufsm_transition t_920a29b7_5375_466c_ac35_9c3a6735d0da = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_c9138d12_f221_4866_863c_0332ab591df9,
    .guard = &g_dbc3dc53_429b_4f24_bac5_d7bd9aeb78dc,
    .source = &s_9dcc0d0a_9027_433a_98a9_6484ee801210,
    .dest = &s_8962e8ae_4db8_4d87_b944_36c1e883fc43,
    .next = &t_8313a454_c083_40eb_a201_b253c3fc2da4,
};

const struct ufsm_action a_86e9ffb9_8c7f_4d5b_ba2e_f51c1f47b6aa = {
    .name = "canvas_edit_state_name",
    .f = &canvas_edit_state_name,
    .next = NULL,
};

const struct ufsm_transition t_8313a454_c083_40eb_a201_b253c3fc2da4 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_86e9ffb9_8c7f_4d5b_ba2e_f51c1f47b6aa,
    .guard = NULL,
    .source = &s_9dcc0d0a_9027_433a_98a9_6484ee801210,
    .dest = &s_4f8688ed_1d77_4105_a8c3_32d2a01b4323,
    .next = NULL,
};

const struct ufsm_state s_9dcc0d0a_9027_433a_98a9_6484ee801210 = {
    .index = 54,
    .name = "Edit",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_5eab8cc6_a546_4d54_8ce1_17ae54205b61,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_57bf38bf_9f31_452c_ae58_04890f81958a,
};


const struct ufsm_state s_57bf38bf_9f31_452c_ae58_04890f81958a = {
    .index = 55,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_8962e8ae_4db8_4d87_b944_36c1e883fc43,
};


const struct ufsm_state s_8962e8ae_4db8_4d87_b944_36c1e883fc43 = {
    .index = 56,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2,
};

/* Transitions originating from 'Delete' */
const struct ufsm_transition t_2213c167_5061_41b8_a38c_85537f9410db;
const struct ufsm_action a_3d8bdfbb_4bf6_4eb3_ae61_2b559a580c50;
const struct ufsm_guard g_0c6ce15e_c154_44d9_a245_e06a16fdb797;
const struct ufsm_transition t_caab11b2_f47c_42b7_a525_d3a227fe5db1;
const struct ufsm_action a_0aec359d_b65a_42f5_8a13_f021b5dae536;
const struct ufsm_guard g_000027ce_24f7_4fb0_9a42_b38f06de0d4d;
const struct ufsm_transition t_7843fc2c_6b48_447c_84b1_84c2c97fbd0e;
const struct ufsm_action a_feb47dbd_4c8a_46c1_a041_e23bcc7e23b1;

const struct ufsm_action a_3d8bdfbb_4bf6_4eb3_ae61_2b559a580c50 = {
    .name = "canvas_delete_entry",
    .f = &canvas_delete_entry,
    .next = NULL,
};

const struct ufsm_guard g_0c6ce15e_c154_44d9_a245_e06a16fdb797 = {
    .name = "canvas_state_entry_selected",
    .f = &canvas_state_entry_selected,
    .next = NULL,
};

const struct ufsm_transition t_2213c167_5061_41b8_a38c_85537f9410db = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_3d8bdfbb_4bf6_4eb3_ae61_2b559a580c50,
    .guard = &g_0c6ce15e_c154_44d9_a245_e06a16fdb797,
    .source = &s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2,
    .dest = &s_4fa41c00_4c8a_427b_aab9_084185816cf2,
    .next = &t_caab11b2_f47c_42b7_a525_d3a227fe5db1,
};

const struct ufsm_action a_0aec359d_b65a_42f5_8a13_f021b5dae536 = {
    .name = "canvas_delete_exit",
    .f = &canvas_delete_exit,
    .next = NULL,
};

const struct ufsm_guard g_000027ce_24f7_4fb0_9a42_b38f06de0d4d = {
    .name = "canvas_state_exit_selected",
    .f = &canvas_state_exit_selected,
    .next = NULL,
};

const struct ufsm_transition t_caab11b2_f47c_42b7_a525_d3a227fe5db1 = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_0aec359d_b65a_42f5_8a13_f021b5dae536,
    .guard = &g_000027ce_24f7_4fb0_9a42_b38f06de0d4d,
    .source = &s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2,
    .dest = &s_a4974753_4d25_4df5_b50d_c2c54682884a,
    .next = &t_7843fc2c_6b48_447c_84b1_84c2c97fbd0e,
};

const struct ufsm_action a_feb47dbd_4c8a_46c1_a041_e23bcc7e23b1 = {
    .name = "canvas_delete_state",
    .f = &canvas_delete_state,
    .next = NULL,
};

const struct ufsm_transition t_7843fc2c_6b48_447c_84b1_84c2c97fbd0e = {
    .kind = UFSM_TRANSITION_EXTERNAL,
    .trigger = NULL,
    .action = &a_feb47dbd_4c8a_46c1_a041_e23bcc7e23b1,
    .guard = NULL,
    .source = &s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2,
    .dest = &s_5eb13eb8_b839_4876_9195_15171db9d107,
    .next = NULL,
};

const struct ufsm_state s_a2a6cb0d_06ba_4737_8da9_15e5abf19fe2 = {
    .index = 57,
    .name = "Delete",
    .kind = UFSM_STATE_SIMPLE,
    .transition = &t_2213c167_5061_41b8_a38c_85537f9410db,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_4fa41c00_4c8a_427b_aab9_084185816cf2,
};


const struct ufsm_state s_4fa41c00_4c8a_427b_aab9_084185816cf2 = {
    .index = 58,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_a4974753_4d25_4df5_b50d_c2c54682884a,
};


const struct ufsm_state s_a4974753_4d25_4df5_b50d_c2c54682884a = {
    .index = 59,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = &s_5eb13eb8_b839_4876_9195_15171db9d107,
};


const struct ufsm_state s_5eb13eb8_b839_4876_9195_15171db9d107 = {
    .index = 60,
    .name = "Final",
    .kind = UFSM_STATE_FINAL,
    .transition = NULL,
    .entry = NULL,
    .exit = NULL,
    .region = NULL,
    .parent_region = &r_f38bf7dc_626b_47b8_bafa_50a13beea4e2,
    .next = NULL,
};

/* Machine API */
int canvas_machine_initialize(struct canvas_machine *machine, void *ctx)
{
    machine->machine.r_data = machine->region_data;
    machine->machine.no_of_regions = 11;
    machine->machine.s_data = machine->state_data;
    machine->machine.no_of_states = 61;
    machine->machine.region = &r_00000000_0000_0000_0000_000000000000;
    ufsm_stack_init(&(machine->machine.stack), 11, machine->stack_data);
    ufsm_stack_init(&(machine->machine.stack2), 3, machine->stack_data2);
    return ufsm_init_machine(&machine->machine, ctx);
}
int canvas_machine_reset(struct canvas_machine *machine)
{
    return ufsm_reset_machine(&machine->machine);
}
int canvas_machine_process(struct canvas_machine *machine, int ev)
{
    return ufsm_process(&machine->machine, ev);
}
